### ISSUE TITLE
Shipping prices by weight

### ISSUE THREAD

**Issue by curaloucura** [mirumee/saleor#1022]
I work with DHL which prices by country and weight as many transporters do, and I need to price heavy orders accordingly.

I don't fully understand the decision of making shipping methods flat in Saleor, as most online shop systems I've worked with do it also by weight. Is this a planned feature?

**Comment by patrys** [comment]
We initially made it based on weight but it turns out it's actually not that common. It is however fairly easy to implement once you know the weight of each product sold.

**Comment by curaloucura** [comment]
Yes, I was just wondering whether it was a design decision or another milestone in the project. I will implement that in my own fork then. Thank you.

**Comment by MacLake** [comment]
My colleagues also don’t want to have a flat shipping rate, since the steps in the shipping rate according to weight are really big, especially when shipping to other countries. So we also need to implement shipping prices according to weight (maybe also size) somehow.
Specifying the weight can be done by extending the saleor.product.ProductVariant, maybe with a fallback value in saleor.product.Product, like for prices. Then I’ve found order.DeliveryGroup.shipping_price. I guess, this is the field to change the calculated shipping price. But where and how? And how do I get the items of the cart or delivery group?

The code is quite readable, but nevertheless it would be much easier to implement this feature with some hints. Is there any explanation somewhere? Has anybody already made a fork with shipping costs by weight?
