### ISSUE TITLE
Adding Tax calculations

### ISSUE THREAD

**Issue by segerpeter07** [mirumee/saleor#1055]
It would be very useful to have tax calculations where admins can add a predefined tax rate, and this is added to the subtotal of the order and shown on the billing page and customer receipts. Any ideas on where I might look to add this feature?

**Comment by MacLake** [comment]
I only found out that [prices](https://github.com/mirumee/prices/blob/master/prices/__init__.py) are named tuples  that have the parts net, gross and currency. On the other hand there is [django-prices.PriceField(models.DecimalField), which just extends DecimalField.
](https://github.com/mirumee/django-prices/blob/master/django_prices/models.py). I am confused because I don’t know how they are related.

Anyway, in order.models.Order.send_confirmation_email() you can get the items of the order, do some tax calculation and create context for the mail:

```
        context = {
            'payment_url': payment_url,
            'items': self.get_items(),
            'total_shipping': self.get_total_shipping(),
            'total': self.get_total(),
        }
```

**Comment by patrys** [comment]
`PriceField` is misnamed as what it really contains is a single amount. We're working on fixing that but since it's such a large change it's progressing very slowly as it's hard to get someone to review the changes proposed: https://github.com/mirumee/prices/pull/21

**Comment by curaloucura** [comment]
how is any active project dealing with Taxes right now?  I see only the VatLayer integration working on that area and that has been inactive for few months. Any pointer if there's a solution for this issue already or there simply haven't been any real project using Saleor until now?

**Comment by elwoodxblues** [comment]
We haven't really used taxes in any of our project based on Saleor so far. This pull request has been hanging for quite a while and it's on our roadmap to review it and finally merge it to Saleor. There is also [django-prices-vatlayer](https://github.com/mirumee/django-prices-vatlayer) library that allows you to fetch tax rates from Vatlayer and apply them to prices.

**Comment by aalvarez** [comment]
Bad news ... without tax , we can't use it

**Comment by maxwhosevillage** [comment]
Would also love to see taxes being implemented in sailor. I think an important feature for professional use. #1929 looks like a good way to go! Just wanted to drop the link here because I was searching myself.

**Comment by Pacu2** [comment]
Tax support was just added in #1929 🎊
