### ISSUE TITLE
StripeCardProvider not rendering the complete button

### ISSUE THREAD

**Issue by PelloMugica** [mirumee/saleor#1056]
We are starting a new brand and we are interested in using Saleor for our online store, until now we have been modifying the frontend without any problem but now when we want to test the payment Gateway we wanted to use Stripe without using the modal but when we used StripeCardProvider the form loaded without the button to complete the payment.
![saleor stripecardprovider without button](https://user-images.githubusercontent.com/29704495/27535008-3f99224e-5a69-11e7-9388-d8876172afb3.png)

**Comment by Satloff** [comment]
Any ideas on how to fix this issue?

**Comment by elwoodxblues** [comment]
It seems that there are two issues:
- `credit_card_expiry_widget.html` is using wrong context names for the inputs, that's why they are not rendered. If you removed this template, Django would use the one from `django-payments`: [link](https://github.com/mirumee/django-payments/blob/master/payments/templates/payments/credit_card_expiry_widget.html). Or you could copy content of `credit_card_expiry_widget.html` from `django-templates` to the one in Saleor, it will work the same plus will allow you to customize the appearance.
- `stripe.html` template is not rendering the submit button.

I'll try to fix those issue and provide a PR, but if you can as well fix it in your codebase by fixing the two templates.

**Comment by elwoodxblues** [comment]
@Satloff The problem should be fixed now.

**Comment by Satloff** [comment]
Nice work @elwoodxblues! All working now. Thanks
