### ISSUE TITLE
Multi-domain (multi-site) support

### ISSUE THREAD

**Issue by rafaponieman** [mirumee/saleor#1068]
It may be desirable to manage several stores from one central location, with separate products and stock records, but one central dashboard. Eventually, there could be some permission assignment that would allow an administrative user to work on a subset of domains.

This may seem overkill, but its very relevant at least when a company manages stores in different countries from one central location (and probably also on other scenarios), and would like to re-use the same templates and avoid having separate users in each system. Furthermore, Wagtail CMS has support for multiple sites, so currently not being able to have multi-site stores makes deployment of multi-site cms alongside an independent store for each site more complicated (if even possible out-of-the-box).

It would be something similar than what has been done for Spree (https://github.com/spree-contrib/spree-multi-domain), and also what's available on Wagtail (with their own Site model).

**Comment by maarcingebala** [comment]
We'll be working very soon on the multi-channel functionality which will allow for something very similar.

**Comment by andrecgro** [comment]
First of all, congratulations for the work you guys are doing, I really believe on this project success.
I'm starting to develop a Shopify like product and have chosen Saleor as the base of my software because:

1. I would like to learn all the techs related to it (Django, React, Python per se, Docker, etc)
2. It was suggested on this blog post https://pagepro.co/blog/multi-tenant-ecommerce-platform-in-three-months/

Therefore, I was working to integrate [django-tenants](https://github.com/django-tenants/django-tenants/blob/master/docs/index.rst) on it and came across this Issue Report when checking the things you are planning to develop.

Is this multi-channel @maarcingebala suggested similar to this multi-tenant approach?

**Comment by maarcingebala** [comment]
Hi everyone, a long time has passed since any activity in this issue - but here we are almost one year later and the multi-channel feature has been implemented in Saleor and it's now production ready 🚀 . Basically multi-channel allows defining product/variant/shipping/plugin availability per channel. Channels can represents multiple stores in the same countries (e.g. different catalog for mobile or web), or they can be different shops in different countries. In the future we will be probably moving more things to be channel-specific.

See the API documentation for more details: https://docs.saleor.io/docs/3.0/developer/channels
