### ISSUE TITLE
Product suggestions / recommendations

### ISSUE THREAD

**Issue by t00ts** [mirumee/saleor#1089]
Saleor looks very promising. We've been looking into it but couldn't find if it includes product suggestions / recommendations "feature" as seen here:

https://www.prettygreen.com/products/mens-classic-fit-stripe-oxford-shirt-1434

This website apparently uses Saleor. Is this feature available out of the box? If not, can it be embedded from some other source? Is it publicly available or should we work on it ourselves?

Thanks!

**Comment by MAkcanca** [comment]
You can start to work on it yourself since this is a publicly available open source project :)
I suggest that you should look into k-Means clustering since it's fairly easy to implement and really efficient on giving product suggestions. Or if you don't have "too many" products, you can just go with tag and category based suggestions.

Have fun!

**Comment by ajinkyakulkarni333** [comment]
Hello Sir! We want a product recommender for a book selling website so how can we implement tag and category based suggestions?

**Comment by maarcingebala** [comment]
This should be implemented as a plugin.
