### ISSUE TITLE
'context must be a dict rather than Context.' error in dashboard views

### ISSUE THREAD

**Issue by nachobonilla** [mirumee/saleor#1094]
I have recently installed for the first time Saleor, but while navigating the dashboard interface i have encountered with several 'context must be a dict rather than Context.' errors in the following paths:

dashboard/products/
dashboard/orders/
dashboard/products/classes/
dashboard/products/classes/
dashboard/settings/1/edit/

Do you have any ideas of what could have gone wrong ?

**Comment by patrys** [comment]
This looks like an artifact of our recent switch to Django 1.11.

**Comment by patrys** [comment]
@Pacu2 Would you mind taking a look? Adding tests that confirm the following views work would also be nice.

**Comment by Pacu2** [comment]
@nachobonilla 
I was unable to recreate this problem on fresh installation, but I suppose it comes from outdated python modules on your instance.
Are you using `virtualenv`? Could you please try updating your [pip packages](https://stackoverflow.com/questions/24764549/upgrade-python-packages-from-requirements-txt-using-pip-command)? 

If this doesn't help, please post complete error log from the console, together with list of all python modules installed (can be done with `pip freeze` command, under Linux).

**Comment by elwoodxblues** [comment]
We've been working with dashboard a lot recently and we didn't came across this error, so I think it might be already resolved. If this happens again, please reopen this ticket.

**Comment by bakeriogit** [comment]
@elwoodxblues @Pacu2 @patrys  Just wanted to let you guys know that I encoutered the same error today.
I tried to update my Saleor fork and merge it with my existing changes but naturally everything went to sh*t really fast. Somehow I managed to recover my old state and got everything working again except for this error. For me it's not the exact same URLs, but most of them match.
I am using a virtualenvironment.
Here is a traceback of the error:
`Environment:


Request Method: GET
Request URL: https://website.de/dashboard/settings/1/edit/

Django Version: 1.11.7
Python Version: 3.5.2
Installed Applications:
['storages',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sitemaps',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.auth',
 'django.contrib.postgres',
 'saleor.userprofile',
 'saleor.discount',
 'saleor.product',
 'saleor.cart',
 'saleor.checkout',
 'saleor.core',
 'saleor.graphql',
 'saleor.order',
 'saleor.dashboard',
 'saleor.shipping',
 'saleor.search',
 'saleor.site',
 'saleor.data_feeds',
 'versatileimagefield',
 'babeldjango',
 'bootstrap3',
 'django_prices',
 'django_prices_openexchangerates',
 'emailit',
 'graphene_django',
 'mptt',
 'payments',
 'materializecssform',
 'rest_framework',
 'webpack_loader',
 'social_django',
 'django_countries']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'babeldjango.middleware.LocaleMiddleware',
 'saleor.core.middleware.DiscountMiddleware',
 'saleor.core.middleware.GoogleAnalytics',
 'saleor.core.middleware.CountryMiddleware',
 'saleor.core.middleware.CurrencyMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware']


Template error:
In template /home/website/saleor/saleor/templates/dashboard/base.html, error at line 31
   context must be a dict rather than Context.   21 :     <link rel="stylesheet" type="text/css" href="{% static "versatileimagefield/css/versatileimagefield.css" %}">
   22 : 
   23 :     {% block custom_css %}{% endblock %}
   24 :   </head>
   25 : 
   26 :   <body class="{% block body_class %}body-home{% endblock %}">
   27 :     <header>
   28 :       <nav class="top-nav" id="top-nav">
   29 :         <div class="nav-wrapper">
   30 :           <div class="right">
   31 :              <ul id="user-action " class="dropdown-content">
   32 :               <li class="user-name">
   33 :                 {{ request.user }}
   34 :               </li>
   35 :               <li class="divider"></li>
   36 :               <li>
   37 :                 <a href="/" target="_blank" class="waves-effect waves-teal">
   38 :                   {% trans "Visit storefront" context "Dashboard top navigation action" %}
   39 :                 </a>
   40 :                 <a href="{% url "dashboard:styleguide" %}" target="_blank" class="waves-effect waves-teal">
   41 :                   {% trans "Style guide" context "Dashboard top navigation action" %}


Traceback:

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  217.                 response = self.process_exception_by_middleware(e, request)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  215.                 response = response.render()

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/response.py" in render
  107.             self.content = self.rendered_content

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/response.py" in rendered_content
  84.         content = template.render(context, self._request)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/backends/django.py" in render
  66.             return self.template.render(context)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/base.py" in render
  207.                     return self._render(context)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/base.py" in _render
  199.         return self.nodelist.render(context)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  177.             return compiled_parent._render(context)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/base.py" in _render
  199.         return self.nodelist.render(context)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  72.                 result = block.nodelist.render(context)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/base.py" in render
  1040.             output = self.filter_expression.resolve(context)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/base.py" in resolve
  736.                 new_obj = func(obj, *arg_vals)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/materializecssform/templatetags/materializecss.py" in materializecss
  16.     return render(element, markup_classes)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/materializecssform/templatetags/materializecss.py" in render
  53.     return template.render(context)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/backends/django.py" in render
  64.         context = make_context(context, request, autoescape=self.backend.engine.autoescape)

File "/home/website/saleor/saleor/saleor_env/lib/python3.5/site-packages/django/template/context.py" in make_context
  287.         raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)

Exception Type: TypeError at /dashboard/settings/1/edit/
Exception Value: context must be a dict rather than Context.`

And a list of my installed packages:
`amqp==2.2.2
anyjson==0.3.3
appdirs==1.4.0
asn1crypto==0.22.0
attrs==17.3.0
Babel==2.3.4
BabelDjango==0.2.2
beautifulsoup4==4.6.0
billiard==3.5.0.3
boto3==1.4.4
botocore==1.5.4
braintree==3.34.0
cairocffi==0.8.0
CairoSVG==1.0.22
celery==4.1.0
certifi==2017.7.27.1
cffi==1.9.1
chardet==3.0.4
click==6.7
colorclass==2.2.0
cryptography==1.7.1
cssselect==1.0.1
cssselect2==0.2.1
cssutils==1.0.1
defusedxml==0.5.0
dj-database-url==0.4.2
dj-email-url==0.0.10
Django==1.11.7
django-absolute==0.3
django-babel==0.6.1
django-bootstrap3==8.2.1
django-cache-url==1.3.1
django-celery==3.2.2
django-celery-results==1.0.1
django-countries==4.1
django-elasticsearch-dsl==0.4.1
django-emailit==0.2.2
django-filter==1.0.4
django-google-analytics-app==3.0.0
django-impersonate==1.1
django-materializecss-form==1.0.1
django-mptt==0.8.7
django-payments==0.11.0.3
django-phonenumber-field==1.3.0
django-prices==0.4.13
django-prices-openexchangerates==0.1.12
django-redis==4.7.0
django-render-block==0.5
django-storages==1.6.5
django-templated-email==2.2.0
django-versatileimagefield==1.6.2
django-webpack-loader==0.4.1
djangorestframework==3.7.3
dnspython==1.15.0
docopt==0.6.2
docutils==0.14
elasticsearch==2.4.1
elasticsearch-dsl==5.3.0
email-validator==1.0.2
Faker==0.7.7
first==2.0.1
freezegun==0.3.9
google-i18n-address==2.0.1
google-measurement-protocol==0.1.6
graphene==1.1.2
graphene-django==1.2.0
graphql-core==1.0.1
graphql-relay==0.4.5
gunicorn==19.7.1
html5lib==0.999999999
idna==2.2
iso8601==0.1.12
jmespath==0.9.0
jsonfield==1.0.3
kombu==4.1.0
lxml==3.7.2
Markdown==2.6.7
maxminddb==1.2.3
maxminddb-geolite2==2015.708
mock==2.0.0
oauthlib==2.0.6
olefile==0.44
packaging==16.8
pbr==1.10.0
pdfrw==0.4
phonenumberslite==8.8.5
Pillow==3.4.2
pip-tools==1.11.0
pip-upgrader==1.4.4
pluggy==0.6.0
premailer==3.0.1
prices==0.5.8
promise==1.0.0
psycopg2==2.6.2
purl==1.3
py==1.4.32
pyasn1==0.1.9
pycparser==2.17
PyJWT==1.4.2
pyparsing==2.1.10
Pyphen==0.9.4
pytest==3.0.5
pytest-django==3.1.2
pytest-mock==1.6.3
pytest-vcr==0.3.0
python-dateutil==2.6.0
python3-openid==3.1.0
pytz==2016.10
PyYAML==3.12
redis==2.10.5
requests==2.12.4
requests-oauthlib==0.7.0
Rx==1.6.0
s3transfer==0.1.10
satchless==1.1.3
singledispatch==3.4.0.3
six==1.10.0
social-auth-app-django==1.1.0
social-auth-core==1.2.0
stripe==1.46.0
suds-jurko==0.6
terminaltables==3.1.0
text-unidecode==1.0
tinycss2==0.6.1
typing==3.5.2.2
urllib3==1.19.1
uWSGI==2.0.14
vcrpy==1.10.3
vine==1.1.4
WeasyPrint==0.41
webencodings==0.5.1
wrapt==1.10.11
xmltodict==0.10.2
`

I already tried upgrading some/all of them but to no avail.

**Comment by Pacu2** [comment]
Hi @bakeriogit,
As far as I can see you still have `django-materializecss-form==1.0.1` installed. 

When upgrading to `Django 1.11` we've dropped that package as it was not maintained, and worked on our fork inside of `Saleor`, in `saleor/core/materializecss`, probably you're using wrong materialize.

Can't tell if that's the only one at the first sight, you should completely uninstall all pip packages, and get new ones from the latest `requirements.txt`
