### ISSUE TITLE
Review requirements and decide which should be updated

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#1107]
At the very least we should update Django to the latest build. Even though we don't use `DEBUG` in production we can't prevent any of our users from doing so.

https://requires.io/github/mirumee/saleor/requirements/?branch=master

**Comment by bravamin** [comment]
Updating django to 1.11.x apepars to require some work according to our light investigation. 

https://docs.djangoproject.com/en/1.11/releases/1.11/#django-template-backends-django-template-render-prohibits-non-dict-context

Identifying and fixing all the places where you included non-dict context will require non-trivial amount of work. Let me know if you think otherwise.

**Comment by bravamin** [comment]
While it may not be a quick thing to update django to 1.11.x, it's probably a good idea to update to 1.10.8 https://www.djangoproject.com/weblog/2017/sep/05/security-releases/ if your site is running with `DEBUG=True` for some reason.
