### ISSUE TITLE
Missing Customer Search in Dashboard 

### ISSUE THREAD

**Issue by kwatog** [mirumee/saleor#1146]
I know there's closed issue on [#218](https://github.com/mirumee/saleor/issues/218) a few years back but I can't seem to find the search function in the dashboard now. was it removed?

If I have hundreds or thousands of customers and would like to get info of a particular customer based on name or email, it would be hard to manually search them page by page.

**Comment by elwoodxblues** [comment]
Hi @kwatog, the issue you are referring to was related to one of the first implementations of the dashboard. Since then we've added a global search field in the dashboard header that looks up products, users and orders. It's hidden when Elasticsearch is disabled, so you have to configure it first (can be easily done using Docker). Unfortunately, currently we have a bug after recent upgrade of Elasticsearch (#1149). We'll try to fix it as soon as possible and then you should be able to use it to search users.

**Comment by kwatog** [comment]
thanks for the update @elwoodxblues 
I actually did not enable elasticsearch yet.
