### ISSUE TITLE
populatedb

### ISSUE THREAD

**Issue by andreyglauzer** [mirumee/saleor#1362]
I'm in trouble, and I do not know what's happening, whenever I give the command

python manage.py populatedb --createsuperuser

I have the following error at the end

Order: #57
Order: #58
Order: #59
Order: #60
Featured products created
Group: Products Manager
Superuser already exists - admin@example.com
CommandError: Unknown command: 'search_index'

**Comment by Pacu2** [comment]
Hi @andreyglauzer!
It's definitely a bug, we've recently created new ES back-end in #1193, looks like the search command file was not added to the PR.

**Comment by andreyglauzer** [comment]
Hello, thank you very much for the feedback.

Is there any way for me to fix it, or should I wait for bug fix?

**Comment by salwator** [comment]
Hi @andreyglauzer, thank you for reporting bug.
Problem is not critical, no functionality should be affected by reported issue. Command 'search_index' is not available when elasticsearch backend is disabled and error above is because of attempt to update search index after populating db. If you want to use search backend please refer to saleor documentation and configure elasticsearch. If it is not your intent, please ignore error until it is resolved.

It's relatively easy to fix so I might do it very soon.
