### ISSUE TITLE
use db mysql error 

### ISSUE THREAD

**Issue by pandabo1985** [mirumee/saleor#1393]
packet.check_error()
  File "/usr/local/var/pyenv/versions/3.4.0/lib/python3.4/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/var/pyenv/versions/3.4.0/lib/python3.4/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1170, "BLOB/TEXT column 'data' used in key specification without a key length")

**Comment by Pacu2** [comment]
Hi @pandabo1985,
We recommend using Saleor with [PostgreSQL](https://www.postgresql.org/), we are using some Postgresql specific fields - like HStore, that's the only supported database at this moment.

**Comment by pandabo1985** [comment]
ok,thanks.

**Comment by parin13** [comment]
any update regarding mysql support @Pacu2 ???

**Comment by NyanKiyoshi** [comment]
@parin13 there won't be any MySQL support. Saleor use multiple Postgres features.

**Comment by OzzyTheGiant** [comment]
This is unfortunate as it limits me due to the fact that the web hosting chosen by the client only has MySQL available. Supporting only PostgreSQL means that clients would have to shell out extra money for either a database instance elsewhere or a cloud server that has it installed internally. I would think that tables would be implemented I'm a way that is database agnostic, just as Django allows this to be.
