### ISSUE TITLE
Document how to update saleor 

### ISSUE THREAD

**Issue by chimeno** [mirumee/saleor#1470]
Considering using saleor for next project. I'm already know it's created to be forked, but since software is an always evolving thing, document how update it would be great.

Also if there are another approach to extend the software which doesn't imply merging problems, would be great to add to the documentation as well.

Examples would be awesome :)

**Comment by elwoodxblues** [comment]
Hey @chimeno, upgrading Saleor is one of the problems that we're still looking for the best answer to. Currently, there is no better way than merging the latest release into your codebase and resolving the conflicts manually. Unless you have done a lot of customizations it shouldn't be that difficult. Saleor is still evolving and I believe we'll eventually come out with a better solution, but for now, that's the only way.

**Comment by patrys** [comment]
I think the best way to merge is to selectively cherry-pick the changes you want. I don't think many stores would welcome a change that replaces the entire checkout process with a different one every couple of months for example.

**Comment by primax79** [comment]
can I suggest to squash your commits before mergin them to master? you have a lot of small commits for a feature, with patches and bugfix, as is normal during the develop

you can squash the commits and expose only the final version, making easier to cherrypick the functionalities

**Comment by maltitco** [comment]
@primax79 the update can also be based on individual releases: [https://github.com/mirumee/saleor/releases](https://github.com/mirumee/saleor/releases)

**Comment by h3** [comment]
What is the reasoning behind packaging Saleor as a project rather than a reusable app?

Because the difficulty in solving that problem pretty much stems from there.

**Comment by h3** [comment]
My internal notes on upgrading, if that can be useful to someone: https://gitlab.com/snippets/1770515

**Comment by johnchendev** [comment]
@h3 , thanks for the guide.

What happens if I'd want to update Saleor when my project is under production?

Do I update Saleor through the upstream on Github, then update the storefront from my host server?

Thanks!

**Comment by maarcingebala** [comment]
Unfortunately, the official answer now is still to do manual upgrades by cherry-picking or merging changes from Saleor to your projects. We're aware of the issue, but as you may imagine, changing the architecture of a project that is five years old and has always been developed as a forkable one is not an easy task. But don't worry, we listen to our community and it's crucial for us to solve this problem, especially if we want to push Saleor even further. This is what we're planning to do (or are already doing 🙂):

- Wrapping the core of Saleor (models and business logic) with a GraphQL API - this will allow us fixing bugs underneath and gradually adding new features. Most of the API is already here; we're now validating it and polishing it up.

- Extracting the storefront to a separate app ([we already have a beta version](https://github.com/mirumee/saleor-storefront)). If it lives as a separate project, you can develop it independently from the backend, which means you can gradually adapt to the new features. To make the customization easier, we want to introduce support for themes.

- Extracting the dashboard to a separate app - this is also partially done ([Dashboard 2.0](https://demo.getsaleor.com/dashboard/next/)). Right now this app still lives in the Saleor' repository, but we want to move it to a separate project. We're aiming to provide all must-have features of typical e-commerce in our dashboard so that you won't have to modify it on your own. 

- Provide a CLI tool that will take care of installing and managing those three independent parts.

We believe that dividing Saleor into independent modules will make the management and update process a lot easier. With every release, we're slowly getting there, but we still need some more time.

**Comment by h3** [comment]
That's awesome news @maarcingebala, I really think every step you planned are in the right direction.

I've done it for a commercial project, we went from full django (for front and back) to django for REST backend with a separate SPA/PWA for frontend.

The task is huge on the frontend side as it's pretty much a full rewrite of css/js, but the reward is equally huge in many regards. Since the rewrite it's now my favorite project to work on, but to be honest [Quasar framework](https://quasar-framework.org/) as a *lot* to do with it.

I cannot stress enough how fantastic Quasar is. I think the last time I was that much excited about a framework is when I discovered django 0.95 back in 2006.

The only point I think might not be necessary is the CLI. Having two components to setup to work on the project might be a little more annoying, but it's not that bad.

This is a recurrent problem with a lot of our projects too, as they grow bigger they need more moving parts to run and they get harder to setup for local dev. To raise the bar even higher, I also need non-programmers to work on projects (designers, translators..) and they usually work on MacBooks or Windows.

The closest thing to a solution I've found is [Koding](https://www.koding.com/). Their approach is really interesting, but running it in the cloud has some tradeoffs and it means I now have a new infrastructure to pay and manage.

I've finally decided to implement my own solution, which is a Proxmox Vagrant box with a Saltstack master, squid and named pre-configured. A YAML file is used to define the project specs and containers are created/started/orchstrated using a saltstack formula.

So my only requirements is Vagrant with Virtualbox, everything else runs inside the VM. This also makes it possible to run multiple instances of the applications (dev mode, production mode). I can setup Django dev server in a single container or run a production like setup with multiple containers or even both.

I'm thinking about open sourcing it, but it's still a barely a prototype at this point..

Anyway .. sorry for the text wall, keep up the good work and happy holidays! ;)

**Comment by sephii** [comment]
The way Saleor has to be installed is a huge blocker for me, because it prevents you for example to integrate it in an existing project, and as it has been mentioned it makes updating very painful. I would love to see Saleor be pip-installable and just being able to add it to `INSTALLED_APPS`.

For the record, [django-oscar](https://github.com/django-oscar/django-oscar/) has a nice way to allow overriding core models ([see their docs for more info](https://django-oscar.readthedocs.io/en/releases-1.6/topics/class_loading_explained.html)).

**Comment by patrys** [comment]
From our experience, updating Oscar is actually more work than doing a `git rebase` because you never see the conflicts. You have to manually compare each and every one of your class overrides with the new version of the base class and you need to check if you're missing any classes that were introduced in between.

That being said, we are looking for ways to extend the Saleor core without modifying its source code. In that regard, I think it would still be closer to how Sentry works. I believe it would be more practical to deploy it alongside your existing project (and have your client application access both) rather than try to merge it into an existing project. As a complete platform, we make many assumptions about how authentication works, what middlewares are executed etc.

**Comment by benjick** [comment]
Any news on this? Saleor looks cool but the installation process isn't very attractive...

**Comment by patrys** [comment]
@benjick The recommended installation process is to use Docker. We publish ready to use Docker images here: https://github.com/orgs/mirumee/packages/container/package/saleor.

Upgrading is something we need to document better, but it should be a matter of getting a newer Docker image and running the migration command.

Forking the codebase and modifying Saleor's core directly (instead of using plugins and apps) is not something we support, so you need to figure your own way to upgrade if you decide to do it.

**Comment by luluhoc** [comment]
@patrys Any news on this? I'm really interested to use saleor for my next projects but the documentation lacks many things, especially production deployment. Are there any news on how to update saleor in 2022 or still nothing?
