### ISSUE TITLE
Facing issue

### ISSUE THREAD

**Issue by marabqa** [mirumee/saleor#1473]
I'm facing an issue on installing Saleor, could you please help me on how to install it and what type of OS should I use. 

By the way I have followed the steps under the documents by preparing everything before to start to install the App but during the installation getting an error.

**Comment by Pacu2** [comment]
Hi @marabqa,
Could you please provide more information? 
On what step did the error appear? What's the error message?

**Comment by marabqa** [comment]
First of all thank you for your reply and may I know what type of OS should I install this App when I try to install npm i webpack -g receiving an error on this step I will try to share with you the error soon.

**Comment by marabqa** [comment]
Hello, 
I'm looking for a proper steps to install Saleor, I'm still getting an error. I have follow the steps which are in the document but still the same.

**Comment by dotslash227** [comment]
@marabqa You need to post the traceback of the errors that your are facing before anyone from the community is able to help you out.

The official documentation: https://saleor.readthedocs.io/en/latest/installation.html is pretty exhaustive and covers everything you need to know to install and run saleor.

It is not mentioned on the docs anywhere, that saleor only support Python3 as support for Python2 was dropped, so please make sure that you are using only Python3 to migrate and run your saleor installation.

**Comment by elwoodxblues** [comment]
Closing due to no response. Please reopen in case of further questions.

**Comment by specialsagar** [comment]
Hi @elwoodxblues , I've recently been trying to install it on my local system and here are the issues I was facing (I am not the same guy as @marabqa)

During the installation of requirements.txt, I had to make use of 'sudo'. If you could suggest a better alternative, please let me know. Post requirements installation when trying to migrate I came across this error.

SyntaxError: Non-ASCII character '\xe2' in file saleor/saleor/core/utils/__init__.py on line 27, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Which i solved by adding the comment # -*- coding: utf-8 -*-

Post which on running python manage.py migrate again I get the error 
-- ImportError: No module named parse
On searching through I came across this thread -- https://stackoverflow.com/questions/29358403/no-module-named-urllib-parse-how-should-i-install-it#37526119

I am not sure if I should do this. I am using ubuntu 16.04


(PS:- this is the first time I have ever raised an issue, in case I got some stuffs wrong please guide me through)

**Comment by dotslash227** [comment]
Saleor has dropped support for Python2, use Python3 to run Saleor.

The errors thst you got are python2.7

Also, use virtualenv to install using pip, to avoid using sudo.

On Jan 3, 2018 01:10, "Sagar Shah" <notifications@github.com> wrote:

Hi @elwoodxblues <https://github.com/elwoodxblues> , I've recently been
trying to install it on my local system and here are the issues I was
facing (I am not the same guy as @marabqa <https://github.com/marabqa>)

During the installation of requirements.txt, I had to make use of 'sudo'.
If you could suggest a better alternative, please let me know. Post
requirements installation when trying to migrate I came across this error.

SyntaxError: Non-ASCII character '\xe2' in file saleor/saleor/core/utils/
*init*.py on line 27, but no encoding declared; see
http://python.org/dev/peps/pep-0263/ for details

Which i solved by adding the comment # -*- coding: utf-8 -*-

Post which on running python manage.py migrate again I get the error
-- ImportError: No module named parse
On searching through I came across this thread -- https://stackoverflow.com/
questions/29358403/no-module-named-urllib-parse-how-should-
i-install-it#37526119

I am not sure if I should do this. I am using ubuntu 16.04

(PS:- this is the first time I have ever raised an issue, in case I got
some stuffs wrong please guide me through)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mirumee/saleor/issues/1473#issuecomment-354856784>, or mute
the thread
