### ISSUE TITLE
Static Files Not Loading

### ISSUE THREAD

**Issue by dotslash227** [mirumee/saleor#1491]
(Please take the time and describe the problem you're having before you propose a solution.)

### What I'm trying to achieve

I am trying to integrate my own template into the saleor framework.

### Steps to reproduce the problem

1.Added static files to the saleor/static folder
2.Changed base.html file

### What I expected to happen

Design changed as per the template

### What happened instead/how it failed

Styles do not appear, although the text does appear.

(Please include a stack trace if this problem results in a crash.)

**Comment by elwoodxblues** [comment]
@dotslash227 What static files exactly have you added? Static files are compiled by Weback. If you've added new JS or CSS files, you have to make sure that they're imported properly in "entry point" files, so that Webpack nows about them. For example, take a look at `saleor/static/js/storefront.js` - all smaller JS files are imported there. The same rule applies to styles.

**Comment by dotslash227** [comment]
Was able to solve it, had to recompile using npm run build-assets
