### ISSUE TITLE
Unify the way addresses are printed in templates

### ISSUE THREAD

**Issue by rafalp** [mirumee/saleor#1563]
Depending on place, Saleor uses one of three templates to print addresses:

- `dashboard/includes/_address.html`
- `userprofile/snippets/address-details.html`
- `userprofile/snippets/address-short.html`

It may be worth exploring the possibilities of reducing this to single template tag that would handle printing in same way across the project.

I've taken note that our dashboard puts some icons and makes links out of the email and phone no. and storefront doesn't, but I'm unsure if doing same thing in storefront would be an issue (in address management perhaps?), and even then unifying address printing just on the storefront's side should be worth it, considered one template seems to reimplement `format_address` template tag with adding phone number and additional `data-` attributes to result, and other one just calls `{% format_address address %}` tag.

**Comment by elwoodxblues** [comment]
I'm personally not convinced that those icons are particularly useful, they are kind of legacy that's been there since the first version of the dashboard. Not sure about the links.

I'd make it as simple as possible and reduce it to single tag `format_address(address, inline=False)` where `inline` is a boolean flag determining whether the address should be rendered in a single line (which is used in few places).
