### ISSUE TITLE
order/success.html never used ?

### ISSUE THREAD

**Issue by dimozaprianov** [mirumee/saleor#1574]
Possibly delete it ?

**Comment by primal100** [comment]
The create password view should probably return a TemplateResponse for success.html. Currently it redirects to the order detail page. 

```python
    if request.user.is_authenticated:
        return redirect('order:details', token=token)
```
I had thought the order success page didn't look right and seeing there is a success.html makes sense.

The success.html does contain client side analytics, so that may have to be removed as I believe the idea is to only use server side analytics??

**Comment by elwoodxblues** [comment]
This looks like a legacy template and could be removed.

**Comment by primal100** [comment]
But there still should be an order success page, no? If the user is unregistered they get a page saying "Your order was successful" but nothing when the user is logged in.

**Comment by elwoodxblues** [comment]
Yes, this flow has to be unified in both cases. I'm just adding an issue about this.

**Comment by primal100** [comment]
Thanks!
