### ISSUE TITLE
Error in the dashboard

### ISSUE THREAD

**Issue by btenaglia** [mirumee/saleor#1670]
I installed the application and all is ok, but when I logued and try to enter in the dashboard I have this error:

![1](https://user-images.githubusercontent.com/2086311/35329352-56628b2a-00de-11e8-9a20-d276237fe0a1.png)

Any idea what is the problem?
Thanks so much!

**Comment by elwoodxblues** [comment]
Hi @btenaglia, it looks that there is an invalid order in your database with the total price missing. I'm not how you got this order as it shouldn't be possible using Saleor's interface. Have you run the `python manage.py populatedb` command? Did you get any errors? I'd recommend recreating the database and populating it again using the above command.

**Comment by patrys** [comment]
Should we correct our schema so it's not possible to create something like that?

**Comment by elwoodxblues** [comment]
`Order.total_net` and `Order.total_tax` are nullable. I'm not sure why - this should be checked and corrected.

**Comment by rafalp** [comment]
I've got some theories on how this may be happening, I'll give them a try.

**Comment by rafalp** [comment]
I've looked around our codebase, played with different things to try repro the issue and it seems that only place that creates order with `total_net=None` is [in our random data generator](https://github.com/mirumee/saleor/blob/master/saleor/core/utils/random_data.py#L450). Everywhere else this is set via `order.total =` setter that expects to receive price object and raises with `AttributeError` otherwise.

Perhaps random error from database/search index or user interruption borked the db population and @btenaglia retried for second time which then passed, but original messed order was left there? 🤔

Either way I'll setup myself a branch that makes those fields non-nullable and see how much of breaking change it would be to require those to be filled.

**Comment by NyanKiyoshi** [comment]
I think, if I recall correctly, the last time I managed to trigger this exact same exception, it was by trying to delete a product that was in an open order and then to go on the dashboard. But I tried to reproduce that, I wasn't able to.

Last time I managed to do it was a week ago. Last merge pull was 6 days ago, maybe something changed.

@btenaglia were you on the latest version of the master?

I'm gonna continue to try to find the source.
