### ISSUE TITLE
Search_index unknow Command

### ISSUE THREAD

**Issue by Efeyabel** [mirumee/saleor#1726]
### What I'm trying to achieve

Link Saleor whit ElastichSearch

### Steps to reproduce the problem

1. Setup ElasticSearch 
2. `python manage.py search_index --rebuild`

### What happened instead/how it failed

Unknown command: 'search_index'

**Comment by elwoodxblues** [comment]
Hi @Efeyabel, in order to use Elasticsearch, you need to:
- set `ELASTICSEARCH_URL` environmental variable pointing to you Elasticsearch instance,
- set `DB_SEARCH_ENABLED=False` to disable default DB search backend

You can also take a look at the search-related settings in the `settings.py` file and [section about Elasticsearch integration](https://saleor.readthedocs.io/en/latest/integrations/elasticsearch.html) in our docs.

**Comment by Efeyabel** [comment]
Now i got another problem.
I connect suscesfully Saelor and Elasticsearch, but... only create 2 indices. 
In documentation says he creates 3 indices:

By default all indexed objects (products, users, orders) are reindexed every time they are changed.

But Saleor is only created 2: 

`myip:/_cat/indices:`

`green open storefront                      tYCtUJz-RoaPB-hU09rZNQ 5 1    1 0  10.3kb  5.1kb
green open users                           opzlkVbpQL6w1e_nMtAsJQ 5 1    1 0   9.1kb  4.5kb
`

And trow me an error when i try to see an article (obiusly)

**Comment by g-londhe** [comment]
The above url

https://docs.saleor.io/en/latest/integrations/elasticsearch.html

isn't working, could you please share the updated URL for the same?
