### ISSUE TITLE
Add contextual markers in translation strings

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#182]
Since translations are enabled, we need to add contextual markers in code, to avoid wrong automatic translations.

**Comment by itbabu** [comment]
Hi @artursmet I'm working on this since I'm translating Saleor into my language.
 
Atm the main thing is sale inside a discount context and sale as noun of to sell.

Related to this i've noticed that:
* some model contextual markers need to be updated or created
* some fields / models are not translated at all

I started some work here so you can see what I mean:
https://github.com/mirumee/saleor/compare/master...itbabu:add-translations

This process will generate few migrations.

Is it ok for you?

**Comment by artursmet** [comment]
Hi @itbabu,

Thank you for your work, looks great. I'll be happy to see this as a pull request in Saleor :)

**Comment by elwoodxblues** [comment]
This is now implemented.

**Comment by itbabu** [comment]
@elwoodxblues contextual markers are not yet implemented into the javascript code :-).

eg. contextual markers are necessary [here](https://github.com/mirumee/saleor/blob/8c3bceb76642ee6e7b6de45f334296ad96ea0898/saleor/static/js/dashboard.js#L219) for italian.

I started some work on it 2 weeks ago.
I'll do a PR soon.

Cheers

**Comment by elwoodxblues** [comment]
Thanks @itbabu
