### ISSUE TITLE
Cannot use images with the same file name when storing on s3

### ISSUE THREAD

**Issue by jamespsteinberg** [mirumee/saleor#1865]
If you upload two different products but their image names are the same when you add them in the dashboard and use s3 for storage. The store only shows the first uploaded photo for both products.

a random string added or replacing the filepath on upload to s3 would be useful

**Comment by jamespsteinberg** [comment]
fixed with a simple setting

VERSATILEIMAGEFIELD_SETTINGS = {
    'image_key_post_processor': 'versatileimagefield.processors.md5'
}

as per
http://django-versatileimagefield.readthedocs.io/en/latest/

**Comment by NyanKiyoshi** [comment]
That would probably be nice to integrate it on Saleor. We could use CRC32 instead of MD5 as well (not shipped by django-versatileimagefield by default) but the difference is not that much important on such small files.

**Comment by jamespsteinberg** [comment]
@NyanKiyoshi I have to update that the image_key_post_processor didn't actually solve the problem, it only seems to be applied to the cropped images so I still have this issue, I just create a unique name top copy and paste on the dashboard when I am about to upload an image as a quick hack.

**Comment by NyanKiyoshi** [comment]
From what I looked inside versatile and django, without overriding or modifying versatile, the only way to change the file name would be by altering the files name (`request.files` or `self.files` in forms) and sum the uploaded file if the form is valid (before calling the super class in `form.save()` then) and assign it to the file name. 

And finally save the form.

I don't think it would be done in Saleor since it's pretty dirty/ hacky. There is probably another and better way to do that.

Depending on your need you can do those changes on your side.

**Comment by NyanKiyoshi** [comment]
Taking a look back at your issue, it seems like versatile is handling that case in local storage.

For example in local storage, upload two `1.jpg`, will result to this:
![](https://i.imgur.com/aU92M3P.png)
![](https://i.imgur.com/ck2C72a.png)

But fails in the case of S3. I'm thinking you should probably open an issue in django-versatileimagefield since it seems to be handled by them.

**Comment by jamespsteinberg** [comment]
@NyanKiyoshi Sorry to bring this back, I tried a lot of things but was not able to make progress. The django-versatileimagefield is not responsive at all. 

I would love to get this working even if it is hacky (it doesn't really matter because its only on the internal dashboard anyway)

So I just have to add a UUID to the product file name before uploading to s3?

In saleor->dashboard->product->views
ajax_upload_image

I am trying to rename the file in request.FILES
```
import os
os.rename('file.jpg', 'file_uuid.jpg')
```

I can't seem to edit the request object properly and when I print it, it doesn't have the full path of the image which I think I need

**Comment by sammyiyke** [comment]
Still having the same issue. Is there a fix for this yet?

**Comment by NyanKiyoshi** [comment]
@sammyiyke this ticket is very old, could you open a new discussion or ticket?

**Comment by jamespsteinberg** [comment]
@sammyiyke @NyanKiyoshi 

Put this function in your models.py

@deconstructible
class UploadToPathAndRename(object):
    def __init__(self, path):
        self.sub_path = path

    def __call__(self, instance, filename):
        # get filename
        ext = filename.split(".")[-1]
        # set filename as random string
        filename = "{}.{}".format(uuid4().hex, ext)
        # return the whole path to the file
        return os.path.join(self.sub_path, filename)

image = VersatileImageField(
        max_length=256,
        upload_to=UploadToPathAndRename("products"),
        ppoi_field="ppoi",
        blank=True,
        null=True,
    )
