### ISSUE TITLE
Place order on behalf of customer

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [mirumee/saleor#1913]
Can we enable to feature to place order behalf of new/old customer and send them the payment weblink

**Comment by elwoodxblues** [comment]
There is the ability to impersonate customers. You'll find it in the Dashboard > Customers > Customer details > Impersonate customer:

![image](https://user-images.githubusercontent.com/5421321/37394461-18ad0a5a-2774-11e8-833c-c2f39407a7c5.png)

This allows you to log in and place an order on customer's behalf. Once you are at the "payment" step, you can copy-paste the current URL and send it to your customers so that they can actually pay. Example order payment link from my local looks like this:

`http://localhost:8000/order/dbd0bef4-1568-44fa-bad5-7dda139d06c6/payment/`

Creating order entirely through the dashboard is on our roadmap.

**Comment by Jeyakumarrathnaselvi** [comment]
Thanks.
