### ISSUE TITLE
Can I host saleor in bluehost, shared hosting plane ??

### ISSUE THREAD

**Issue by chiranjitkuiry** [mirumee/saleor#1986]
I am new to django and python  and I am really curious about can I host this django project into bluehost shared hosting plan ??

**Comment by rafalp** [comment]
Speaking from personal experience, when shared hosting says "python" on its website, but that comes after "php" or "WordPress", it means they are using FCGI to run clients apps that they have setup for PHP, but they also have read somewhere that you can use FCGI to run Python or Ruby too, and those two languages area already installed in their OS, so they are advertising those to...

...but trying to run python app under such setup is really terrible experience, and you'll be much better served going for VPS that gives you guarantees on resources and ability to setup your own WSGI stack, like [NGINX + UWSGI](http://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html) or Apache with [mod_wsgi](https://modwsgi.readthedocs.io/en/develop/).

To give you better idea how terrible it is to run python things on shared hosting, take a note that most popular solution for doing that, [flup](https://pypi.python.org/pypi/flup/1.0) hasn't been updated since 2007, doesn't support Python 3 and Django has dropped support for it in 2013, with [some good reasons behind it](https://groups.google.com/forum/#!topic/django-developers/oGmD8LvLTPg/discussion).

Thanks!

**Comment by chiranjitkuiry** [comment]
Thanks for your time,
It really saves me a lot of time.
