### ISSUE TITLE
Figure out why connection field edges `node` fields are optional

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#1998]
Currently all connection fields have `edges` typed as:

```graphql
edges: [WhateverEdge]!
```

And the edge itself has:

```graphql
node: WhateverNode
```

Where you'd expect to get:

```graphql
edges: [WhateverEdge!]!
```

and

```graphql
node: WhateverNode!
```

Current `edges` definition makes it legal to return the following response:

```json
{
    "edges": [null, null, null, { "node": "whatever" }]
}
```

Current `node` definion makes it legal to respond with an edge that says:

```json
{
    "cursor": "1234567890",
    "node": null
}
```

**Comment by maarcingebala** [comment]
This turned out to be a problem which I discovered when generating TS types with `apollo-codegen`. The current schema results in TS types which allows `edges` and `node`s inside them to be `null`, which I guess is not correct in GraphQL API. Those types require us to put additional null checks, where there is no possibility for null value (e.g. empty connection returns empty list, not null value).

I looked in the Graphene source code and found two places responsible for that:
- [EdgeBase](https://github.com/graphql-python/graphene/blob/master/graphene/relay/connection.py#L64) defines a node which is optional (no `required=True`)
- [edges](https://github.com/graphql-python/graphene/blob/master/graphene/relay/connection.py#L80)  defines a non-null list of objects, while it shuold also requires the objects to be non-null: `Field(NonNull(List(NonNull(edge))))`.

I'm afraid to I'll have to hack the `Connection` class and try to override it to fix the issue.
