### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#2095]
Implement compliance with GDPR. @patrys is already working on a detailed list of changes to add in Saleor. Once we have it, we'll create specific issues with details.

**Comment by patrys** [comment]
Let's start a project for this so I can file notes and you'll convert them to issues as you see fit.

**Comment by patrys** [comment]
https://github.com/mirumee/saleor/projects/8

**Comment by patrys** [comment]
"Cookies" are not the right term here. There are different kinds of cookies. For example the session cookie is used to keep track of the cart and we don't need a separate agreement to do that since this is the main reason of your visit. Tracking cookies on the other hand are used to gather information that is not critical to fulfill our obligations so they do need an explicit consent and cannot be enabled by default. I think it's more useful to think in terms of processing goals rather than focusing on the means.

**Comment by maarcingebala** [comment]
I think we can close this issue, since we have [this project](https://github.com/mirumee/saleor/projects/8).
