### ISSUE TITLE
Hosting Recommendatrion

### ISSUE THREAD

**Issue by jeromelocson** [mirumee/saleor#2122]
Hi All:

Any hosting recommendation for Saleor? I have GoDaddy Dedicated Hosting (Linux). Will that work?

Thanks,
Jerome

**Comment by Pacu2** [comment]
Hi @jeromelocson, 
Usually we host our solutions on AWS, but Heroku might be an option as well - deploy is really simplified due to our preset configuration ('Deploy to Heroku' button). 

Everything depends on what you need, are you ready to pay a little bit extra for PaaS, to save some setup time, you aim to scale big in the future or you just want to host a shop for a local company. 

Dedicated Hosting should be fine, as long as you have reasonable amount of RAM and CPU available.
Keep in mind that AWS provides some great security in their infrastructure, that's something you might be missing on Dedicated Hosting. Also, expanding  and adding extra services in the future might be easier than with AWS than with Dedicated Hosting.

**Comment by Pacu2** [comment]
Please reopen if you have any further questions
