### ISSUE TITLE
Deploying Saleor an Amazon Web Services Elastic Beanstalk

### ISSUE THREAD

**Issue by dano000** [mirumee/saleor#2142]
I'm attempting to deploy a Saleor app to Amazon Web Services using Elastic Beanstalk. I'm almost there, but for some reason webpack does not seem to be found. I tried to: 

- build the assets using `yarn run build-assets` - this does not work.
- run the `npm build` + the `collectstatic` standard stuff.

but I'm a bit lost as to why it doesn't find the webpack file. I have attached the error output below:
![django-saleor-aws](https://user-images.githubusercontent.com/5187084/39521546-49a819b0-4e52-11e8-9f0c-149134e71de5.png)

Any help would be greatly appreciated!

**Comment by NyanKiyoshi** [comment]
Hi!

When you say that you ran `npm build` and `collectstatic`, on what side did you run them? From your local source directory or your EC2 instance (eg: through `.ebextensions` or SSH)?

If you ran this command from your source code, I would guess that `ebs-cli` did not upload the assets since they are in the `.gitignore` and `ebs-cli` is using `git` (which means you have to commit, etc.).

You could drop the static directory from the `.gitignore` and then add and commit the static files (after the `collectstatic`). It should work, and reduce the deployment time (and also a few issues with webpack and your EC2 instances that may occur, depending on your configuration).

Also, are you deploying to a docker instance or directly to an instance with its own OS? That would really help us, if you let us know the target environment (docker, ubuntu-server, redhat, etc.)!

**Comment by dano000** [comment]
Hi NyanKiyoshi!
I ran `npm build` and `collectstatic` locally (ie. on my ThinkPad).

I also tried to install node and npm on the instance from source (I know that this is bad, and you should do it via `.ebextensions` but it was just to see if I could get it to work). - It didn't work :(

I totally didn't realise the gitignore had so many things in it, thank you for that! I took a look to see if I can deploy by just adding the static files and the `webpack-bundle.json`

I wasn't using docker, just directly to an instance (Elastic Beanstalk, not EC2 directly, if that makes sense) - just standard latest Amazon Linux, Python 3.6.

So this _partially_ worked in that, it now actually displays something (because the webpack json file can be found) but now the storefront.css is not found (and presumably the same with dashboard).

Do you know why this is the case?

Thanks again for your help! Much appreciated!

**Comment by NyanKiyoshi** [comment]
I would really guess this has something to do with the `.gitignore` as well.

Also, you should probably not be running Saleor with `DEBUG=True` on EBS.
Since `DEBUG` is True, I would guess you need to remove the ignore on `/saleor/static/assets/`.

And, I don't think this is a bad thing to compile assets before deployment. Since we are deploying a build, it makes sense to not have to recompile on each instance through `.ebextensions`.

**Comment by patrys** [comment]
Are you using `uwsgi`? If so it is configured to serve static files from `/app/static` by default as that's the path used by our Docker containers. If you deploy directly to an EBS machine, update your `uwsgi.ini` file (the `static-map` directive).
