### ISSUE TITLE
Documentation of "Docker for Development" not working

### ISSUE THREAD

**Issue by carstenblt** [mirumee/saleor#2353]
Forgive me if this is too obvious, I'm completely new to Docker and this took me a few minutes to figure out. However, the documentation says:

5. Prepare the database

$ docker-compose run web python manage.py migrate
$ docker-compose run web python manage.py collectstatic
$ docker-compose run web python manage.py populatedb --createsuperuser

Which does not work. What works is 
$ docker-compose run web /app/virtualenv/bin/python manage.py ...

since the container is setup with a virtualenv.

**Comment by nobism** [comment]
Is your `virtualenv` activated? If so then I think it should have worked, otherwise you're just specifying exactly which python interpreter to use. If you run `python --version`, `python3 --version` and `python3.6 --version` you might get 3 different answers, that's the main reason why `virtualenv` was created.

On a related note, I'm trying to run up Saleor using the production instructions, but I have a feeling that they're incomplete as well. I'm also new to Docker so it's taking me some time to work out what's going on.

**Comment by carstenblt** [comment]
Well, running the container with
$ docker-compose run xxx
apparently does not activate the environment. So either it's specifying the correct interpreter or changing the Docker container to do that automatically - which I don't know how to do.
$ docker-compose up
however does switch to the virtualenv correctly, the server starts up without problems.

**Comment by nobism** [comment]
What error message(s) were you getting exactly? Also, do you happen to have a folder called `virtualenv` in the project's base directory? The `Dockerfile` says to copy everything from the base directory into the container, that's the only way that you could possibly run python from `/app/virtualenv/...`.

**Comment by carstenblt** [comment]
Oh, yeah:
`Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'`

No, and as far as I can tell the Dockerfile does not copy anything but runs pip within the container.

**Comment by patrys** [comment]
This is a valid problem and was introduced by #2308

**Comment by carstenblt** [comment]
#2357 fixes it for me.

**Comment by maarcingebala** [comment]
Should be resolved by #2362.
