### ISSUE TITLE
Add image thumbnails to ProductImage type

### ISSUE THREAD

**Issue by dominik-zeglen** [mirumee/saleor#2445]
API should be able to return image thumbnails in specified size - something like this:
```
{
    product {
    images{
      edges{
        node{
          thumbnail(x:256, y:256)
        }
      }
    }
  }
}
```

This could help us avoid situations where API consumer gets 10 `4000px x 7000px` images just to put them in `120px x 120px` containers.

**Comment by patrys** [comment]
As we won't be able to provide an exact match for 99% of requests, I think this would make more sense:

```graphql
{
  node {
    thumbnail(width: 100, height: 100) {
      height
      width
      url
    }
  }
}
```

or maybe:

```graphql
{
  node {
    thumbnail(type: "product_gallery")
  }
}
```

**Comment by maarcingebala** [comment]
As @oldPadavan noticed, we already have this feature in our API. We should only change it to accept one of few predefined sizes. In settings.py we have `VERSATILEIMAGEFIELD_RENDITION_KEY_SETS` settings which defines what sizes are pre-generated for products, we could use that.

**Comment by patrys** [comment]
I think `url(size: 120)` is easier (notice I've changed it to only accept one value) as otherwise the client has to know the mapping of names to sizes (which cannot be determined within the same query) and has to include a function mapping desired sizes to setting names. I think it's easy enough for the backend to do the matching (select equal size if exists, otherwise select closest larger size if not more than 2 times larger, otherwise select closest smaller size).

**Comment by oldPadavan** [comment]
Does it mean it's necessary to restrict the sizes to those defined in `VERSATILEIMAGEFIELD_RENDITION_KEY_SETS`?

**Comment by patrys** [comment]
Yes, we do not want to allow API clients to create arbitrary sizes at will. A malicious user could easily generate terabytes worth of thumbnails by asking for all possible combinations of widths and heights.
