### ISSUE TITLE
newbie - 400 error

### ISSUE THREAD

**Issue by brw31415** [mirumee/saleor#249]
running:
 ubuntu 14.04
1.7 django
2.7.6 python

I get this when starting , using $python manage.py runserver:

Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  No migrations to apply.
(trusty)user@localhost:~/myproject$ python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
April 01, 2015 - 22:30:52
Django version 1.7, using settings 'saleor.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[01/Apr/2015 22:31:02] "GET / HTTP/1.1" 400 26
[01/Apr/2015 22:31:02] "GET /favicon.ico HTTP/1.1" 400 26

**Comment by javierwilson** [comment]
Same here. It works if DEBUG=True, though. Try:
$ DEBUG=True python manage.py runserver

**Comment by javierwilson** [comment]
If DEBUG is off, just try http://localhost:8000/ instead of http://127.0.0.1:8000/ ALLOWED_HOSTS only includes "localhost" and not "127.0.0.1" see https://github.com/mirumee/saleor/blob/master/saleor/settings.py#L245

**Comment by ninja-neer** [comment]
Hi @patrys  @javierwilson , got similar issue with  @brw31415 but figured that localhost was used.

However, my issue is around serving the static files like the 404 on: 
[17/Apr/2015 16:05:02] "GET /static/dist/js/bootstrap.min.js HTTP/1.1" 404 1676
[17/Apr/2015 16:06:22] "GET / HTTP/1.1" 200 5883
[17/Apr/2015 16:06:22] "GET /static/dist/js/less.min.js HTTP/1.1" 404 1661
[17/Apr/2015 16:06:22] "GET /static/dist/js/jquery.min.js HTTP/1.1" 404 1667
[17/Apr/2015 16:06:22] "GET /static/dist/js/bootstrap.min.js HTTP/1.1" 404 1676

Logic seems to work, but just making it a bit readable is my issue due to the static files. I tweaked the static dirs etc but still unsuccessful. Any ideas?

Thanks

**Comment by bogdal** [comment]
Hi @ninja-neer. Try to install `npm` dependencies, get appropriate libs through `bower` and run  `grunt` task.
```
npm install
./node_modules/.bin/bower install 
./node_modules/.bin/grunt
```
This is missing part of docs.

**Comment by ninja-neer** [comment]
Hi @bogdal I'll try as soon as I got the chance... Let you guys know... 
Thanks heaps.

**Comment by patrys** [comment]
Closing this as all seems well.
