### ISSUE TITLE
Docker - Error reading ./webpack-bundle.json.

### ISSUE THREAD

**Issue by apburton84** [mirumee/saleor#2506]
### What I'm trying to achieve

Follow the install instructions.

### Steps to reproduce the problem

1. docker-compose build
2. docker-compose run web python3 manage.py migrate
3. docker-compose run web python3 manage.py collectstatic
4. docker-compose run web python3 manage.py populatedb --createsuperuser
5. docker-compose up
6. Goto http://127.0.0.1:8000

### What I expected to happen

I expect to see the Saleor homepage

#### What I actually happens

    Error reading ./webpack-bundle.json. Are you sure webpack has generated the file and the path is correct?

**System information**
Operating system: MacOS High Sierra 10.13.3
Browser: Chrome 67.0.3396.99 (Official Build) (64-bit)
Docker Engine: 18.06.0-ce
Docker Compose: 1.22.0
Docker Machine: 0.15.0

Running ```yarn run build-assets``` does not resolve the issue, as yarn is not installed on the docker container.  #874 

It seems that ```/app/webpack-bundle.json``` is not being copied from build-nodejs (node:8.6.0) as instructed in the Dockerfile.

    COPY --from=build-nodejs /app/webpack-bundle.json /app/

```npm run build-assets --production``` which runs ```webpack -p --progress``` should have created ```/app/webpack-bundle.json```?

A log of the output of docker-compose up

    Step 25/35 : COPY --from=build-nodejs /app/webpack-bundle.json /app/   ---> 68c7bcd63e49

and docker history shows the ```/app/webpack-bundle.json``` being copied to the container.

    68c7bcd63e49        20 minutes ago      /bin/sh -c #(nop) COPY file:8bbd3e3203b94232…   1.18kB

https://stackoverflow.com/questions/51672994/saleor-docker-error-reading-webpack-bundle-json

**Comment by michaeldel** [comment]
The actual issue here is that the `/app` directory is mapped to the project dir through a volume because of this:
```yml
services:
  ...
  web:
    ...
    volumes:
      - .:/app:Z
```
Because all of these files indeed are in the built image (here the user is `root` because I have remove that `useradd` in `Dockerfile`):
```
$ docker run -it $(basename $(pwd)) ls -lh | grep -E 'bundle|static'
drwxr-xr-x 11 root root 4.0K Aug 10 12:19 static
-rw-r--r--  1 root root 1.2K Aug 10 12:16 webpack-bundle.json
```
One solution is to compile static files from host:
```
$ npm install && npm run build-assets --production && npm run build-emails --production
```
You should then be able to proceed with the usual `docker-compose` commands:
```
$ docker-compose run web python manage.py migrate
$ docker-compose run web python manage.py collectstatic --no-input
$ docker-compose run web python manage.py populatedb --createsuperuser
$ docker-compose up
```
There are unfortunately no proper way to "ignore" some paths in Docker volumes:
- https://forums.docker.com/t/how-to-exclude-subfolders-when-using-volume/16508
- https://stackoverflow.com/questions/33624212/how-to-exclude-some-paths-when-mounting-the-volume
Even though some tricks my exist, I have not tried them:
Some tricks might exist but are not applicable here (because one cannot directly mount volume over existing files)
- https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder

**Comment by maarcingebala** [comment]
Please update to the latest version of Saleor. After all the Docker changes this should be already fixed. If not, please reopen the issue.

**Comment by chetabahana** [comment]
> The actual issue here is that the `/app` directory is mapped to the project dir through a volume because of this, thus overwriting container's:
> 
> ```yaml
> services:
>   ...
>   web:
>     ...
>     volumes:
>       - .:/app:Z
> ```
> 

`Important: When using bind mounts with services, selinux labels (:Z and :z), as well as :ro are ignored. See moby/moby #32579 for details.`

Reference: [Docker: Use bind mounts - Configure the selinux label](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label)

**Comment by theanhvo** [comment]
i have not config with Docker , please
