### ISSUE TITLE
Payments GraphQL API

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#2556]
Saleor needs GraphQL API to support payments in new storefront.

After some research on the market, we observed that most of the sites use PayPal, Stripe or Braintree as a payment processor.

We decided to integrate Braintree as a default payment gateway in Saleor because it has decent, well-documented API and also supports PayPal, ApplePay, GooglePay and of course standard credit card payments.

We aim to have this integration well documented to make it easy to integrate with a different payment provider.
Saleor's API will also support multiple payment providers at a time.
By design, this API won't process any credit card details in the backend, so full PCI audit won't be required.

Proposed graphQL API structure for payments:

Mutations
- `completeCheckoutWithCard(
	gateway: BRAINTREE,
	token "1234",
	amount: "120",
	address {},
)`
- `deleteStoredPaymentMethod(payment_method_token)` - deletes stored payment method

- `authorize(payment_method_token, amount)`
- `refund(payment_method_token, amount)`
- `void(payment_method_token)`

Queries:
`payments` - list of all payments
`payment(id)` - get a payment by ID

**Comment by patrys** [comment]
What's a `payment_method_token`, isn't that just `id: ID!`?

Does `completeCheckoutWithCard` need to take `amount`? Do we want to accept partial payments? Do we trust client to decide the amount?

I feel like `authorize`, `refund`, and `void` should have a common suffix like `voidPayment`, otherwise it's not obvious what they do.

How is `authorize` different from `completeCheckoutWithCard`? Don't they both authorize the card? I think you maybe meant `capture`?

Maybe `void` and the like could take an order ID and a payment method ID? They will need to include the order in their response.

Not sure what use cases we have to browse `payments` outside of an order? This looks like a debug tool more than something staff needs.

**Comment by artursmet** [comment]
As I mentioned above - the API layout and endpoint names are only proposal at the moment. Some of them may change in the future or could be even dropped.

You're right - `completeCheckoutWithCard` should take an amount because partial payments should be supported.
