### ISSUE TITLE
order_status_change gets fired multiple times during OrderCapture

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#2818]
`order_status_change` function (signal) get's fired multiple times during OrderCapture.
As a result, we have duplicated events:
ORDER_FULLY_PAID -> SEND_PAYMENT_CONFIRMATION -> ORDER_FULLY_PAID -> SEND_PAYMENT_CONFIRMATION -> ORDER_CAPTURED

I think that analytics report is sent twice as well, signal should be reworked so it won't be fired more times than necessary.

Also, can't see any test for this function.

**Comment by oldPadavan** [comment]
`order_status_change` is connected to `django-payments`'s `status_changed` signal which is called from `change_status` method of the `BasePayment` class:
https://github.com/mirumee/django-payments/blob/34d0f7597fd9273d6d20922d8b9ffa355e265d7f/payments/models.py#L81-L89
When `Payment.capture` is called it first calls `capture` method of provider and then if returned `amount` casts to True calls `change_status` which sends the signal. 
https://github.com/mirumee/django-payments/blob/34d0f7597fd9273d6d20922d8b9ffa355e265d7f/payments/models.py#L136-L144
But some providers like `default` also call `change_status` inside its `capture` method:
https://github.com/mirumee/django-payments/blob/36d704233c9f2a0729cad7e4df7e32d628182c43/payments/dummy/__init__.py#L66-L68
As a result the signal it called twice inside `django-payments`. So there's a question whether it's a desired behavior for `django-payments` to send its signal twice, in other words whether the actual problem is in `Saleor` or in `django-payments`?

**Comment by maarcingebala** [comment]
I guess this issue doesn't occur anymore as we've dropped `django-payments` in Saleor.
