### ISSUE TITLE
Should I use Django's Auth User model?

### ISSUE THREAD

**Issue by chadsaun** [mirumee/saleor#286]
I was wanting to add first and last name fields to my user and as I got looking I realized that Saleor has it's own User model and doesn't inherit from Django's Auth User model (which has a first and last name).  So my first thought was to use Django's User model, but then I wondered if Saleor did that for a reason.

Should I use Django's Auth User model?  Or should I stay away and just add my own first and last name?  Or is it just client preference?

**Comment by patrys** [comment]
We have rolled a custom user model because we don't want users to deal with usernames. You can extend Saleor's user model with whatever fields you find useful (hey, maybe it makes sense for Saleor to provide those — what is your use case?) or you could revert to Django's default implementation, which may require sign in/registration views to be slightly customized to reflect that but otherwise should be a straightforward task.

**Comment by chadsaun** [comment]
Ah ok that makes sense now.  I missed that when comparing the models. We just have an e-commerce site and would like to store names as well for each user.
