### ISSUE TITLE
Variant attributes order

### ISSUE THREAD

**Issue by weronka** [mirumee/saleor#2878]
### What I'm trying to achieve

I want to create a custom variant picker in the storefront where all attributes except the first one will be flattened (more details in https://github.com/mirumee/saleor-storefront/issues/36).
So attributes in the variant editor in dashboard should be displayed in the same order as API returns them to have more control on how variant picker will eventually look like.

**Comment by Pacu2** [comment]
@weronka Is it a blocker or a cosmetic issue for now?

**Comment by weronka** [comment]
@Pacu2 For now it's more cosmetic but without this feature in the future user won't be able to work with such custom variant picker correctly.

**Comment by maarcingebala** [comment]
`AttributeValue` model already uses the `SortableModel` class which adds ordering functionality, we have to only make sure that values returned by the API actually use that ordering. 
As for ordering of `Attribute` instances, `SortableModel` won't work because we have to sort attributes within a product type, not globally.

**Comment by frosenb** [comment]
what's the status on this?

**Comment by NyanKiyoshi** [comment]
There is no plan yet for implementing it. But if anybody want to open a PR for it, feel free! 😄

**Comment by maarcingebala** [comment]
We're working on it as a part of #4351.
