### ISSUE TITLE
Optional, elasticsearch-powered full-text search

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#291]
This is not top priority as rolling your own seach is quite easy to do but ideally we want to support this inside the codebase.

Searchly provides a free tier of two indices and 5MB of storage to play with so we can support full text even on Heroku.

**Comment by patrys** [comment]
Talked to Honza, his opinion is to require elasticsearch and provide vagrant + salt provisioning config for running everything locally as this will also help Windows users.

**Comment by 3ka5-cat** [comment]
IMHO, search is `must have` feature and it would allow to implement more user-friendly navigation through category tree.

What do you think about elasticsearch in docker image instead of vagrant and separate catalog app, based on django-haystack? I think it will be more cheap in terms of development hours, also more flexible and SOA-way.

**Comment by patrys** [comment]
We've agreed to start with Haystack and the project already uses Docker so the plan to use Vagrant is no longer relevant.
