### ISSUE TITLE
Multiple values for an attribute

### ISSUE THREAD

**Issue by detouched** [mirumee/saleor#2991]
### What I'm trying to achieve
I wonder if an attribute with multiple values for a product would make sense.

Imagine a store selling t-shirts with two-color prints, and each design (which is a product) is available in few color schemes, and the set of color tuples is unique for every product. What I'd want to make available for the customers is when they pick a color (as a regular attribute picker), show all t-shirts that have that color on their print.

It wouldn't work with two synthetic attributes: you can't really select each of the colors, there's only very limited number of combinations, so the variant selector(s) wouldn't make sense – this is similar to [#2102](https://github.com/mirumee/saleor/issues/2102#issuecomment-401327128).

### Describe a proposed solution
So this sounds like multiple values for a single attribute for each product variant. A combination of values defines a variant. The variant selector might be a dropdown instead (it might quickly become very wide otherwise), but that's a less important question.

Does this make sense? Maybe I'm doing something wrong and can set it up in a different way?

**Comment by maarcingebala** [comment]
This problem is entirely valid and what you propose totally makes sense. There shouldn't be any problem with handling multiple values in the dashboard, also in the storefront's variant picker, we could render combined values simply as separate choices (e.g. "black", "white", "black/white").

There is one thing that I'm not sure of - we use HStore field to store the attributes which are assigned to a variant e.g.:
```
In [3]: variant.attributes
Out[3]: {'4': '7'}
```
which means that the attribute of ID 4 has a value of ID 7. This is fine, but in case of multiple values we would have to store a list, e.g.:
```
{'4': ['7', '8']}
```
Is that possible with HStore? If not, we can always transform this field into a JSON (I guess). What do you think @patrys?

**Comment by patrys** [comment]
hstore is a string to string map type so we'd have to switch to JSON. Not sure how that would affect faceted search in the storefront. Custom indexes would be required. Distinct queries are a bit tricky as in JSON both objects and arrays are ordered types so `{"4": ["7", "8"]}` is not the same as `{"4": ["8", "7"]}`.

**Comment by akshaykay** [comment]
@patrys @maarcingebala Is this still in your feature pipeline? 

Here's our situation: 

We have books that could be co-authored by multiple authors. In our filter on the product listing page, we would like to be able to select one of the authors of a particular book (that has multiple authors) and have the book show up.

**Comment by patrys** [comment]
It's on our radar, we're seeking to eventually match the product editing capabilities of Magento 2.

**Comment by NyanKiyoshi** [comment]
This is now a feature! 🎉
