### ISSUE TITLE
SSO / LDAP

### ISSUE THREAD

**Issue by joshuacox** [mirumee/saleor#3037]
### What I'm trying to achieve

use a centralized identity server to connect saleor users with other services.

### Describe a proposed solution

integrate https://pypi.org/project/django-auth-ldap/

### Other solutions I've tried and won't work

I'm actively looking for solutions and was wondering if someone had already conquered this issue.

**Comment by maarcingebala** [comment]
We did integration with LDAP in one of our projects based on Saleor some time ago and everything worked fine. We had to use the `django_auth_ldap.backend.LDAPBackend` as authentication backend and customize it a bit to the specific business rules we had.

**Comment by joshuacox** [comment]
Are there any components from your previous project you plan on integrating back into Saleor overall?


Notes that might be useful if I or anyone else ends up implementing this:

Poking around it looks like the [account backends](https://github.com/mirumee/saleor/tree/master/saleor/account/backends)
which use the [social-auth-core](https://github.com/python-social-auth/social-core/tree/master/social_core/backends).

So adding another oauth2 provider shouldn't be that hard as there are a plethora of examples in there.  Including the [gitlab](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/gitlab.py) 
and the generic [one](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/oauth.py)

**Comment by maarcingebala** [comment]
We don't plan to port that code into Saleor. As I said, due to specific business rules most of that was our customizations to the standard `django_auth_ldap.backend.LDAPBackend`. Unfortunately, we also don't have time to work on that now as we are busy with other priorities. But I'll try to elaborate a bit about the concepts we had back then, so maybe it will guide you if you were to implement that in your system.

Basically, we combined two authentication backends. First, we had the standard username/password authentication provided by Django. Secondly, we had the `LDAPBackend` from `django-auth-ldap` and we used that to authenticate users if the first authentication failed. After successful LDAP login, we saved users' data into our database, so on every consecutive login we would already have their data and could use our database to authenticate them.

There was also a script running periodically (implemented as a Django management command) that synced users between LDAP and our database. It allowed us to remove accounts from our database if they were removed/disabled in LDAP. It also saved calls to LDAP when users were logging in for the first time, as we already synced their data earlier.

I hope this helps you understand how LDAP authentication might work with Django/Saleor. As you can see, the authentication mechanisms are pretty flexible in Django and you can implement a lot of custom rules in it.

**Comment by joshuacox** [comment]
@maarcingebala thanks for the input!  Your scenario sounds more like the end goal I had in mind, i.e. Saleor syncing with an LDAP backend.  Specifically I'd like to sell kubernetes services, whereas someone buys a subscription level and then has access to spawn clusters with resources according to their level.  The existing OAUTH stuff certainly gets me part of the way there with authentication of identities, but I do need some sort of push or sync back out to the LDAP for authorization of newly enabled subscriptions.
