### ISSUE TITLE
Use Draft.js + Draftail to handle rich text fields

### ISSUE THREAD

**Issue by patrys** [mirumee/saleor#3067]
### What I'm trying to achieve
We currently use Medium Editor for basic rich text features. We'd love to have something easier to style (not storing HTML in the database).

### Describe a proposed solution
I propose that we use [Draft.js](https://draftjs.org/) to handle the editing and rendering aspect in React apps (dashboard and the new storefront). For Django views we can use [Draftail](https://www.draftail.org/) to render things server-side.

### Other solutions I've tried and won't work
We've evaluated most existing WYSIWYG/WYSIWYM editors.

**Comment by pooyakn** [comment]
Sorry for my late response. I was busy for the last few days.
I'll be working on it from now on.

So we want to use [Draftail](https://github.com/springload/draftail) for React side editor, and possibly [draft.js exporter](https://github.com/springload/draftjs_exporter) for converting the Draft.js schema (that Draftail uses) to HTML for showing Draft.js data correctly in Django views?
cause I checked and Draftail is a client side editor built on Draft.js.
and as a result we want to save new data as JSON?

Am I correct?

**Comment by patrys** [comment]
Yes, sorry if there was any confusion.

**Comment by maarcingebala** [comment]
I'd like to revisit this issue since we're going to build new pages management section in Dashboard 2.0. Are we sure that we want to go with Draft.js? From quick research, I see there are some other options, some of them quite popular as well:
- https://www.slatejs.org/#/rich-text
- https://quilljs.com/

**Comment by maarcingebala** [comment]
E.g. one thing that I find problematic with our current editor is no capability to edit raw HTML. Oftentimes our editor produces strange output that I didn't expect and being able to edit some HTML manually is often very convenient.

Since Draft.js uses JSON underneath that might be not possible, although I saw some plugins that enable HTML import/export.

**Comment by maarcingebala** [comment]
Other possibilities:
- http://megadraft.io
- https://github.com/ProseMirror/prosemirror
