### ISSUE TITLE
No way to easily create multiple variants

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#3208]
### What I'm trying to achieve
Improve product variant creation flow 

### What I expected to happen
When adding variants to the product I need to go to
Product -> variant edit -> created variant -> product -> variant edit

I think that placing floating "add" button on variant details page would simplify the flow significantly, specially when one is creating several variants one by one

**Comment by maarcingebala** [comment]
In the Dashboard 2.0 we should add the "Add variant" button at the bottom of the variant selector as on the design below:
![image](https://user-images.githubusercontent.com/5421321/50596116-6c3e6f80-0ea3-11e9-9eb1-b1c65809485e.png)

**Comment by maarcingebala** [comment]
Since we'll be touching this part I'd like to improve the way the product thumbnails are rendered here. Now it renders like this:

![image](https://user-images.githubusercontent.com/5421321/54676347-d3fa7300-4b00-11e9-8a62-adadcaacc8fe.png)

Unless you specifically assign an image to a variant, a placeholder icon is shown which in my opinion looks a bit like "loader" or missing image. In fact, when there is no variant image we always render the default product thumbnail in the storefront. We could do the same here. Query to get the product thumbnail is:

```
product {
  thumbnail {
    url
  }
}
```

**Comment by maarcingebala** [comment]
![image](https://user-images.githubusercontent.com/5421321/54676751-a9f58080-4b01-11e9-8b99-92de3876484c.png)

The message here is not clear - it says that images are not available while there are product images that I can select from after clicking "Choose photos". I think that instead we should have a help text here: "Select a specific variant image from product images."

"No images available" should be displayed within the "Choose photos" modal if there are no product images at all.
