### ISSUE TITLE
Pages with custom template 

### ISSUE THREAD

**Issue by johnmclives** [mirumee/saleor#3348]
Hi guys, I read on Saleor documentation that you can create pages direct from Saleor dashboard.

That part is clear. 

However, I get confused when I need to create custom pages with different views etc. 

For example, if I need to create custom landing pages that doesn't use the standard template, what then?

Hope someone can enlighten me. Thanks!

**Comment by maarcingebala** [comment]
Hey @johnmclives, there is the ability to add static pages from the dashboard and link them in the storefront menus. To do that, go to the Dashboard and take these steps:
1. Go to the "Pages" section > Click on the "plus" button and create a new page.
![image](https://user-images.githubusercontent.com/5421321/49144400-97aac900-f2fd-11e8-8cdd-6009b8ceed65.png)

2. Go to the "Navigation" section > Select the menu (by default there are two - "navbar" and "footer" > In "Menu Items" section click "Add" > Create a new menu item by selecting your new page in the "Link" field.
![image](https://user-images.githubusercontent.com/5421321/49144353-7813a080-f2fd-11e8-93c6-308f80bfa163.png)

3. Go to the storefront - your static page should be available in the menu navigation menu.

As for the landing page - currently, we don't have a dashboard tool to organize it. In order to change the default one, you have to customize [its source code](https://github.com/mirumee/saleor/blob/master/templates/home.html).

**Comment by johnchendev** [comment]
Thanks @maarcingebala , what about changing colors and all that? I read in the documentation that you shouldn't touch the files directly to edit the code. In that case, how would I go about doing it?
