### ISSUE TITLE
Integrity Error when adding categories after populatedb

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor#3389]
### What I'm trying to achieve
Adding categories after having generated sample data with `populatedb`.

### Steps to reproduce the problem
1. Generate sample data with `populatedb` command
2. Add 7 categories from the admin dashboard

### What happened
On the 7th, 8th and 9th categories added, there was an Integrity Error message saying that those `pk`s already existed in the database. This is caused by the fact that after running populatedb, 3 categories are added with pk 7, 8 and 9 rather than 1, 2 and 3. I haven't investigated all the other tables to see which ones have this as well. But it looks like the products table will also be affected by this bug. It starts from pk 62.

**System information**
Operating system: Windows 10
Browser: Firefox 63

**Comment by michaljelonek** [comment]
This is intended behaviour by Postgres/Django<sup>[1](#footnote1)</sup> and since we specify PKs in our fixtures there's not much we can do to fix it on our side. Changing PKs to arbitrarily high numbers would alleviate the issue as it would be harder to reach high PKs, but it doesn't solve the issue, as it would be still technically possible to get such high PKs.

What I would suggest though is to use Django's `sqlresetsequence`<sup>[2](#footnote2)</sup>, which generates SQL for resetting the sequences, but that in turn would move the counter after the objects we create, so the free PKs before (1 to 6 for categories for example) would stay unused.

In a real production/non-dev environment I imagine you wouldn't use `populatedb` in the first place and provide your own objects. So the question is if this is something that we want to do (by increasing PKs) or just provide a troubleshooting section to solve this issue with `sqlresetsequence` for example?

<a name="footnote1"><sup>1</sup></a>: https://docs.djangoproject.com/en/2.1/ref/databases/#manually-specified-autoincrement-pk
<a name="footnote2"><sup>2</sup></a>: https://docs.djangoproject.com/en/2.1/ref/django-admin/#django-admin-sqlsequencereset

**Comment by maarcingebala** [comment]
`populatedb` is used only for local development, but it looks like a bug if you run the script, tries to add a subcategory in the dashboard and it breaks. Would that be a good idea to extend `populatedb` and reset DB sequences after each run?

**Comment by michaljelonek** [comment]
@maarcingebala personally I don't see why not, wouldn't do us any harm. Although might be wise to control it with a flag to at least be able turn it off in case it breaks in some random situation I can't think of right now. I could go ahead and add it if we agree on that then?

**Comment by maarcingebala** [comment]
I'd give it a try. I'd enable it by default and have a flag to optionally disable this behavior.
