### ISSUE TITLE
Staff should be able to edit orders even if order is finished

### ISSUE THREAD

**Issue by tiberiuichim** [mirumee/saleor#3540]
Staff should be able to edit orders even if they're not in draft. Real-world case: customers make an order, then they realize they haven't added a product to the order, or they don't want some other product. They contact staff, because they can't edit their order on the site, now staff cannot edit the order because it's not draft.

**Comment by maarcingebala** [comment]
It is by design that confirmed orders aren't editable and Saleor isn't the only e-commerce platform that uses this approach. There are two ways to solve the problem in your scenario:
- user can place another order with additional items
- staff can refund and cancel the order and the customer can place a new one.
