### ISSUE TITLE
Multi stores for partners

### ISSUE THREAD

**Issue by aktywnitu** [mirumee/saleor#3551]
### What I'm trying to achieve
I would like to create ecommerce platform for sellers.

### Describe a proposed solution
Multi dashboards and one storefront..

**Comment by hairychris** [comment]
Reaction Commerce had this feature in v1 but have ripped it out for v2 due to the maintenance burden. 

You could hack something together with django-tenant-schemas as suggested by https://github.com/mirumee/saleor/issues/1912 but you wouldn't have a shared storefront.

What's changed since then is the GraphQL API, using that you could probably make a frontend that pulled from multiple tenant backends but it would be non-trivial.

**Comment by aktywnitu** [comment]
OK. Thanks for answer. 
And thanks for info about this maintenance burden in Reaction Commerce with this feature.
Good to know that Reaction Commerce don't support multi vendors now.
I will try do it in the simplest way as possible.  I prefer some Saleor customization, than many apps instances. Other possible solution is meta app, but it also make thinks complicated.

**Comment by hairychris** [comment]
Reaction Commerce do support it right now, they've dropped support in 2.0.0 which is in RC stage due to the extra maintenance and testing burden it was placing on their team. 

This is probably something a lot of people want however so if there is a way to do it cleanly that would be awesome. Platforms currently are run by a lot of giant companies who charge a large fee. It would be great if Saleor could help wrestle some of that control away and spur the growth of lots of new platforms.

**Comment by PSNick** [comment]
Shame, I was drooling at the sight of saleor only to find out it doesn't support multi-vendors. Reading a bit I saw a post from Marcin that mentioned it is a planned feature for 2019, though not Q1 from the looks of it.
https://medium.com/saleor/saleor-2-0-release-graphql-first-headless-e-commerce-1330f2151585

**Comment by aktywnitu** [comment]
@maarcingebala, so multi-vendor feature is in roadmap or not?

**Comment by maarcingebala** [comment]
Since we're getting a lot of questions about that, we will investigate how much effort and changes to the current codebase it would require to support that. The case of Reaction is very interesting in this context and we will have to look at it as well.

Our goal for Q1 is closing features gap between the SPA storefront and dashboard. If everything goes fine we will start adding new features in Q2. Multivendor might be one of them, but as I said, it first requires thorough research.

**Comment by aktywnitu** [comment]
Thanks Marcin.
I will do also my own research.
What does SPA mean?

**Comment by maarcingebala** [comment]
SPA stands for single page application and by that, I was referring to the [Storefront 2.0](https://github.com/mirumee/saleor-storefront) which is implemented entirely in React.

**Comment by ljcljc** [comment]
It would be great if we can support multi stores, I am looking for a solution like that.

**Comment by dnk8n** [comment]
Also keen on the multiple stores idea.

**Comment by maarcingebala** [comment]
Closing in favor of #1251, also read our update on this on Spectrum: https://spectrum.chat/saleor/general/saleor-multi-vendor-when-this-feature-will-release~5c665517-170f-45b3-94f4-ae9f7d344ac9?m=MTU2MDc1NTExMTA3MA==

**Comment by toppylawz** [comment]
Oh I wish the version 2.0 now supports multi-store possibility.
