### ISSUE TITLE
Support creating order from checkout without paying in GraphQL API

### ISSUE THREAD

**Issue by jxltom** [mirumee/saleor#3564]
### What I'm trying to achieve

It looks like the checkout API can only create order by ```checkoutComplete```. But this API will also charge the payment otherwise error will be raised. How about supporting creating order from the checkout without paying? Then the users could goto their order list and pay later.

**Comment by maarcingebala** [comment]
Well we support such flow in Storefront 1.0 so maybe it should be also possible in API. At this moment I'm not sure what flow exactly is assumed in Storefront 2.0 and if we can change that. @mociepka What do you think?

**Comment by jxltom** [comment]
If you don't like the idea of having unpaid order, I think we should provide an API which can filter out the checkouts with proper shipping/billing address which are ready to pay.

**Comment by jxltom** [comment]
One more thing is that unpaid order can be used to hold the stock which make sure the products will not be out-of-stock. The problem with the checkout is that it can not hold the stock. I can create a checkout and pay later, but it could be out-of-stock when I actually pay for it. This feels very annoying for users.

So I take the unpaid order as the situtation when you put the products into your basket in supermarket. The products won't be out-of-stock and you won't hold these products forever. The order is marked as paid when you actually pay for it. And the order is cancelled when you leave your groceries on the conveyor belt and leave.

The unpaid order can be created manually like storefont 1.0 and it will holds the stocks for all the products. We can set a strategy such as cancelling the order if the user doesn't pay within a specific time period.

**Comment by mociepka** [comment]
@jxltom I agree that we should introduce filters like that in the API.

Blocking stock is no go as a default store behavior in my opinion. It is very inconvenient for the sellers. In addition, If you introduce case like that someone could block your whole store by one cart :).

Overall e-commerce needs to earn money it is relevant who will buy your last product. I know that is not polite for end users but sellers create stores.

**Comment by jxltom** [comment]
Just to elaborate, the cart shouldn't block the stock at all. But the unpaid order would block it. Personally, I prefer the idea that an unpaid order will be created when creating payment from the checkout, just like the storefront 1.0 did. This is very convenient for the customers since they can hold the products and pay later. It is quite common for online stores (actually this is the case for all the online shops I have ever seen). Of course, these unpaid orders would block the stock, so usually there is a strategy which will cancel and restock automatically as countdown (usually 30 minutes or 1 hour)

**Comment by maarcingebala** [comment]
We cannot allow blocking stock through unpaid orders. This may not be a big issue for small shops but if you have many users and there is a sale (e.g. Black Friday), a malicious user could block products by creating unpaid orders, causing significant losses for the shop owners.

This approach is an optimization towards shop managers rather than customers, as it greatly reduces their problems with order management (no need to deal with unpaid orders).

What is important in this flow is that once a customer enters checkout, we store it in the database (I don't remember now for how long and if or when we delete them). They can return to those checkouts and modify them, place them at a later time or even send it to someone else. We're also planning to add support for tracking abandoned checkouts to trigger some mailing or give discounts in order to encourage customers to return.

**Comment by jxltom** [comment]
You think unpaid order with blocked stock but with **a counterdown which will automatically cancel the order and restock the products** still has these issues?

Actually this strategy is quite common for shops even for very large stores such as amazon.cn.

The main problem with unpaid order without blocking stock is that it is quitely unfriendly to users. The user thought he create a order and want to pay later but the store may out of stock when the customer actually pays for it.

So I prefer the idea of creating a unpaid-order in ```CheckoutPaymentCreate``` just like storefront 1.0 did. This order will hold the stock and the customer can pay later. The customer should also be able to **cancel** it from his account page instead of dashboard. To further optimized this flow, we can add a counterdown strategy for unpaid orders in further development.

**Comment by jxltom** [comment]
After rethink about it, probably it still has malicious attack issues for unpaid order with blocked stock since the attacker can still create huge unpaid orders even they can be automatically cancelled. Maybe those large online stores has more techniques to prevent it, such as by forbidden creating too many unpaid orders from one user or one same IP. But anyway I still think this is the right way for the checkout flow.

**Comment by maarcingebala** [comment]
I'll close this issue since we're not planning to change the checkout flow in the API in the nearest future. We've chosen a particular approach that we want to settle in Saleor and validate how it works in the long term.

**Comment by sagital** [comment]
I am resurrecting this  because I also think the  payment  should be independent of the order and the order `paymentStatus` should reflect this. 

There are at least two situations when the client won't pay for the order at creation time.

* Cash On Delivery - a common scenario where the user pays when he receives the goods 
* Bank Transfer - when the user will pay independently of the checkout process, also common in business to business scenarios when an client pays after a fixed period of time.

I can use a dummy gateway and fake charge the whole sum before creating the order but this creates some complications down the road, and also send an email to the client about the payment which would be kinda confusing (don't know if this is configurable though).
