### ISSUE TITLE
Multi currency

### ISSUE THREAD

**Issue by timuric** [mirumee/saleor#3572]
Anyone had experience setting prices in multiple currencies per product? 
Usually other e-commerce platforms have plugins that add such functionality and admin controls. 
I am wondering how would one achieve similar functionality extension with Saleor?

**Comment by Pacu2** [comment]
@timuric Saleor is meant to be forked by design. Fork it and adjust it to your needs.

If you want to continue using `django-prices-openexchangerates` package, I imagine that you could create a dashboard panel, where one can set `ConversionRate`s by hand (django-prices-openexchangerate's model holding conversion rate for currency pairs). 

If setting a conversion rate is not enough, and you want to be in the full control of conversion rates, you could set a proxy same as our `TranslationProxy` but for the prices. This way you could detect the user's region and display price in a currency that a user is most likely to use.

No need to use a proxy if you're planning to use a limited number of currencies, in such case they could live within `Product`/`ProductVariant` as they do currently, you could just add additional fields like `price_gbp`, `price_usd`, `price_inr`, and display them accordingly.
