### ISSUE TITLE
Saving images to disk not compatible with docker and clusters?

### ISSUE THREAD

**Issue by nixxon111** [mirumee/saleor#3644]
I've recently tested saleor in a kubernetes cluster in Google Cloud, and at first I had some issues with images which seem to have been solved just recently (thumbs up).
However, there is an inherent issue with saving the images to disk when trying to use containers (which by default do not share Disk). 

Possible solutions:
1. Saving image-data to database
2. Saving to online Filestorage (such as AWS S3)
3. Shared Persistent Disk accessible to all containers
4. Don't use docker

Have any of these posibilities been discussed?

I tried solution 3 in google cloud, and it seemed quite complex, I was unsure how "scalable" that solution is, and whether it will be complicated to set up for each new saleor storefront.

**Comment by maarcingebala** [comment]
@artursmet / @michaljelonek Do you have any recommendations on how to approach the problem?

**Comment by michaljelonek** [comment]
I believe we do allow serving both media and static files from AWS S3. If you take a look here: https://docs.getsaleor.com/en/latest/deployment/s3.html.

As for the docker solution, without using an external service like S3 the only other way is to share a volume between services. Both celery and web have a requirement to share media files. However with that I can't help as I don't have much experience with Google Cloud. 

As for storing files in database, well.. it's been a hot topic since BLOB storage was invented 😉. There are pros and cons, but personally, I don't think the image data we store is worth the time and effort to store it in a database. This would increase the database size and increase the time (and size of) to make and restore backups. Images don't change that often, but depending how often you would make backups all the image data would be included. This would also make it potentially problematic to use different services.

**Comment by MikkelScheike** [comment]
Thanks for the answer. I have been dying to see the response asked in this thread.
I think it would be nice if Saleor would be more agnostic towards hosting and the scripts in the solution. Maybe it would make sense to also offer GCP and Azure support out-of-the-box? 

I would gladly assist on the GCP part anyway.
