### ISSUE TITLE
Reuse Storefront 1.0 payment logic in API

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor#3652]
We need to unify the way of creating payments between Storefront 1.0 and API (and Storefront 2.0 consequently). Storefront 1.0 uses `start_payment` view which creates a new `Payment` object and calls the `process_payment` function. This function knows which gateway operations to perform for each gateway.

Similar flow should happen in API. Currently, in the API we have `checkoutPaymentCreate` which is used by Storefront 2.0. The mutation underneath only implements creating a new `Payment` instance but it seems to be missing the logic that is implemented in `start_payment`.

From that perspective this mutation is no different from the storefront's view - they both should trigger the payment processing flow which should be identical in both cases. 

@michaljelonek / @jxltom - You both had a significant impact on the shape of payments in Saleor, so I'd like to have your feedback on that.

**Comment by jxltom** [comment]
Actually storefront 1.0 and current API has different logic on payment. The storefront 1.0 is creating a order first, creating payment assiged to order and then pay. The API is creating payment first, creating order assigned by the payment and then pay. So some changes in ```CheckoutComplete``` API probably needs to be made:
- Checking the existent of payment in ```CheckoutComplete``` and validness. There is a case that ```CheckoutPaymentCreate``` is not calling before ```CheckoutComplete```. There is an another case that the payment probably has already be fully-refunded in dashboard. In this there is no need the charge the payment again.
- If payment is ready to pay, assign checkout's payment to order's payment, otherwise many methods such as ```is_fully_paid``` can not be used.
- Decide should ```CheckoutComplete``` create new order everytime or ```get_or_create```. If the a new order is created everytime, how can we determine the order has already been fully-paid? I think we might need ```get_or_create```.
- After get the order, use ```check_order_status``` to check order shipping address and is order is fully paid. This prevents the order is paid multiple times.
- Calling ```gateway_process_payment``` directly instead of ```gateway_authorize``` and ```gateway_capture```. The ```payment.token``` passed from ```CheckoutPaymentCreate``` is used in ```gateway_process_payment``` directly.
- Decide should the order be deleted if payment fails in ```CheckoutComplete```. If they are not deleted, ```get_or_create``` instead of ```create_order``` should be used. I prefer not deleting them since ```get_or_create``` might have better performance than deleting and recreating (but I didn't do the benchmark and it might have other side-effects).

This is just some loose thoughts, discussion is definitely welcomed.
