### ISSUE TITLE
Successful transaction in stripe does not populate cc payment fields

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor#3875]
### What I'm trying to achieve
Get card details (ex. last 4 digits) from Payment object when using stripe gateway.

### Steps to reproduce the problem
1. Use stripe gateway
2. Pay with card
3. `cc_last_digits`, `cc_brand`, `cc_exp_month`, `cc_exp_month` are empty in Payment object.

### What I expected to happen
Those data should be taken from `gateway_response`.

**Comment by jxltom** [comment]
It is because only a token is passed from frontend to backend during payment in stripe. All the data including credit card brand, last digit, etc. are tokenized. There is no need to expose sensitive data such as credit card information to backend during payment. This makes the payment safer. The docs relate with stripe.js in https://stripe.com/docs/stripe-js might be useful to explaining this.

**Comment by krzysztofwolski** [comment]
@jxltom thats not true. Gateway response has those data and its not considered sensitive.

**Comment by jxltom** [comment]
@krzysztofwolski You're right. I thought you are referring the data posted but you are talking about gateway response. Yeah, it will be nice to update payment if gateway response has updated data. Currently, only transactions are created by gateway response but payment is not updated.
