### ISSUE TITLE
Filters are not applied on the fly

### ISSUE THREAD

**Issue by ipsingh06** [mirumee/saleor#3879]
### What I'm trying to achieve
I am trying to achieve the behaviour observed in the demo (https://demo.getsaleor.com/en/) where filters are applied as soon as they are selected.

### Steps to reproduce the problem
1. Run the docker image (https://docs.getsaleor.com/en/latest/customization/docker.html) on master branch
2. Browse to the local application
3. Click on Apparel
4. Select the filter Shoe Size > 39. Product listing does not change. In the online demo the listing updates right away.
5. Click 'Update Results'. The listing now updates.

### What I expected to happen
I expected the listing to update as soon as the Shoe Size > 39 filter was selected, like it does in the online demo.

**System information**
Operating system: Ubuntu 16.04.5 LTS
Browser: Google Chrome 71.0.3578.98

**Comment by maarcingebala** [comment]
Hey, take a look at the `demo` branch. We use a bit different implementation of category page over there - it's implemented in React and uses GraphQL API to dynamically update results based on your filters. We've added it a long time ago as our first experiment with GraphQL, but on `master` we kept the basic, static version of that page which requires resubmitting in order to view changes.
