### ISSUE TITLE
Sorting by price does not take discounted price into account

### ISSUE THREAD

**Issue by ipsingh06** [mirumee/saleor#3889]
### What I'm trying to achieve
Sorting by price on the category page should take the discounted price into account.

### Steps to reproduce the problem
1. Run a fresh copy of the docker image for development.
2. Browse to the category page for Apparel (http://localhost:8000/en/products/category/apparel-9/)
3. Sort by "price ascending".
    The items do not appear in ascending order of price.

### What I expected to happen
I expected the items to appear in ascending order of price.

**Comment by LeBenLeBen** [comment]
I'm not sure the issue comes only from the discount, even with that taken into consideration the order seems to be still off, see Pineapple and Bean juice below for example.

![Capture d’écran 2019-06-18 à 13 15 28](https://user-images.githubusercontent.com/793344/59677857-367c1180-91cb-11e9-9d9b-2d3553f8aa2b.png)

**Comment by NyanKiyoshi** [comment]
Yes, the issue is that they get sorted by the undiscounted price instead of the discounted price.

**Comment by korycins** [comment]
This will be solved by #4416

**Comment by maarcingebala** [comment]
This issue was solved with PR #4416 which introduced `minimal_variant_price` field that stores the lowest prices of a product.
