### ISSUE TITLE
Add Gift Cards

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#3899]
Gift Cards should be another payment method. Staff should have an ability to create Gift Cards from the dashboard.

Proposed fields:
- initial_balance: the initial balance of the card
- balance: current balance of the card
- is_active: flag indicating if gift card can be used
- code: unique code of the gift card
- created
- activated: date when card was activated. I imagine that cards can be created beforehand, printed and activated once customer buys them from the store.

Things to consider:
- Endpoint for a customer to check the current balance of the card
- Way for bulk-creating gift cards
- Ability to send the gift card to the customer after creation

**Comment by NyanKiyoshi** [comment]
Maybe the user account could have a balance that gets populated from the gift card?

**Comment by krzysztofwolski** [comment]
Since Gift Card is considered a valid payment method, implementation needs to have advanced monitoring/logging needed. Every action which alternates balance needs to be logged with previous state, actual state, date/time and author of changes.

When implementing this feature, additional reporting will be also needed:
- reports on how much money is left on cards/spend
- if cards have an expiration date, then reporting on old vouchers will be needed

Other needed features: 
- panel for customer service which will allow refunding gift cards
- filter orders by card code (helpful when looking for abuses)

**Comment by Pacu2** [comment]
Also, there should be no ability to discount Gift Card, if sold as a separate product in the storefront @fowczarek

**Comment by NyanKiyoshi** [comment]
If is a feature now.

**Comment by Boquete** [comment]
@NyanKiyoshi  what's the current state of gift cards? Is it already implemented? Is there any docs about it?

**Comment by maarcingebala** [comment]
There are some basic backend implementation and mutations to create gift cards, but there is missing dashboard UI plus the ability to actually sell gift cards in the store. So it's not really usable yet. We're currently planning the roadmap for the next few months and I think proper gift card implementation will be high on our priorities list.

**Comment by JannikZed** [comment]
Hey @maarcingebal,  Is there another open issue for the ”sell gift cards” we can follow? We are highly interested in that feature :)

**Comment by maarcingebala** [comment]
Hey, I don't see any other issue for that. We have this feature on our internal roadmap but TBH I'm not sure when we'll be able to work on that as we're now mostly focused on Saleor Apps architecture and multichannel feature. However, we could prepare a detailed description of how we would see this implemented, maybe the community could help us with it.
