### ISSUE TITLE
Ability to order products in a collection

### ISSUE THREAD

**Issue by Pacu2** [mirumee/saleor#3900]
### What I'm trying to achieve
As a store admin, I'd like to have more control over how the products are displayed in the storefront, so I can put bestsellers or products that I want to get rid off at the top of the page

**Comment by NyanKiyoshi** [comment]
I should have enough time to start working on it tomorrow. If so, I will assign myself tomorrow. Otherwise, the next day.

So if someone wants to take it, they can assign themselves (otherwise there won't be anything left for anyone to work on!).

I will probably start thinking and digging around it tonight, and implement it in my dreams!
