### ISSUE TITLE
Tests for counting db queries in GraphQL queries and mutations

### ISSUE THREAD

**Issue by korycins** [mirumee/saleor#3946]
### What I'm trying to achieve
I want to have some tests that will give me a better perspective for usage of DB queries under graphql API.  Now we don't have any information about numbers of queries hitting DB. Most of the fields have optimization but even this I would like to have explicit logic to validate that it works as expected. Also, it would be helpful during any refactor of any graphQL logic.

### Describe a proposed solution
It would be great to have some basic tests to validate number of DB queries executed under a given graphql view.

**Comment by NyanKiyoshi** [comment]
Do you have an idea on how we would check if the query was performed in a correct number of queries? Would we check that the number of queries is lower than a given number? If so, how would we determine the way to do so?

Anyway, there are two available fixtures:
- `django_assert_num_queries`;
- `django_assert_max_num_queries`.

The other way would be to retrieve the query count through the `CaptureQueriesContext` context manager (`len(...)` of the context will give the number of queries).

**Comment by NyanKiyoshi** [comment]
We still don't have a clear idea on how to "test" the query count. I started working on something, I will discuss my ideas and current progress in our next meeting.

Overall, I feel like the best way to "test" the performances, would be to define some benchmark tests (a new page, outside of `tests/` maybe a name close from golang with a `tests_bench/` or something like that).

So instead of doing useless assertions saying "I want this queries to perform in N queries or less", we would generate a report and see if our changes are actually improving the query count or not.

So, at the end, we would have a table showing us every differences between two commits (e.g. the parent tree, master vs the latest commit of the current tree). We would have a huge list of tests, and some red or green colors on the results depending on how well they performed.

I would assume that we would run those tests only once per commit/build. Probably on the latest LTS django and latest supported python. As the python version shouldn't affect the number of queries.

Then, only problem, it may not be enough to only focus on the query count. We could do some time based tests, but that would be more time consuming. That's something that we could dig up some other day.

In final words, the pytest bench tests will be structured the following way:
```
tests_bench/
  |- conftest.py
  |- products/
        |- test_queries.py
        |- test_mutations.py
  |- orders/
        |- test_queries.py
        |- test_mutations.py
```

Then the rapport would look like something like this:

```
## Products
### Queries
| test name       | Queries count <parent name> (<hash number>) | current <hash> | diff |
| --------------- | ------------------------------------------- | -------------- | ---- |
| List products   |                                           5 |              3 |   -2 |
| Product details |                                          11 |             10 |   -1 |
```

This would, of course, support parametrized tests. Which could be really useful and powerful to test many cases.
