### ISSUE TITLE
Unable to edit attribute values

### ISSUE THREAD

**Issue by timuric** [mirumee/saleor#3988]
### What I'm trying to achieve
When adding attribute values it is impossible to save data since the system is trying to create a new attribute which already exists, instead of trying to update the attribute.

### Steps to reproduce the problem
1.  Open existing attribute
2. Add attribute value

### Screenshots
![image](https://user-images.githubusercontent.com/4006792/56359808-f4dae480-61e2-11e9-885b-16b7e3f0bec9.png)
```Attribute already exists within this product type.```

**Comment by NyanKiyoshi** [comment]
Hi!

Could you check your are on the latest version of saleor? (make sure to rebuild the dashboard as well, just to make sure).

I don't manage to reproduce.

Feel free to provide any more guidance.

**Comment by khalibloo** [comment]
Yes I can confirm this bug is still present. I can edit product attribute values, but not variant attribute values. I've attached a screenshot of my product type.
![image](https://user-images.githubusercontent.com/6402969/61030364-4358e300-a3ce-11e9-897e-ab2aa4ff2816.png)

**Comment by maarcingebala** [comment]
I still cannot reproduce the error, I'm testing on the latest `master` and I'm able to edit existing values, both for product and variant attributes. Can you provide more detailed steps to reproduce it?

**Comment by khalibloo** [comment]
I'll dig some more and see if it affects all of my product types or only some. In the meantime, I found this in the network response for the error. The status is a 200.
![image](https://user-images.githubusercontent.com/6402969/61033226-10b1e900-a3d4-11e9-88ef-7cbb017e2c35.png)

**Comment by khalibloo** [comment]
I found that this bug happens when I use a name like "Size" which is used by other product types. When I use an attribute name that is not used anywhere else, it works fine.

**Comment by khalibloo** [comment]
Please let me know if additional information is needed to reopen this.

**Comment by maarcingebala** [comment]
Can you inspect in the database/console what values are already defined for the attribute that you're trying to edit? Maybe you do have an attribute of that slug but the UI isn't showing it? I keep testing it but still, I'm able to add size attribute.

**Comment by khalibloo** [comment]
Sure. In this example, I have the following product type (obtained from the browser's network console)
```json
[
  {
    "data": {
      "productType": {
        "id": "UHJvZHVjdFR5cGU6MTI1",
        "name": "AADebug Test",
        "hasVariants": false,
        "isShippingRequired": true,
        "taxRate": "STANDARD",
        "__typename": "ProductType",
        "productAttributes": [],
        "variantAttributes": [
          {
            "id": "QXR0cmlidXRlOjc0",
            "name": "Size",
            "slug": "size",
            "values": [
              {
                "id": "QXR0cmlidXRlVmFsdWU6MTU5",
                "name": "mini",
                "slug": "mini",
                "__typename": "AttributeValue"
              },
              {
                "id": "QXR0cmlidXRlVmFsdWU6MTYw",
                "name": "med",
                "slug": "med",
                "__typename": "AttributeValue"
              },
              {
                "id": "QXR0cmlidXRlVmFsdWU6MTYx",
                "name": "maxi",
                "slug": "maxi",
                "__typename": "AttributeValue"
              }
            ],
            "__typename": "Attribute"
          }
        ],
        "weight": { "unit": "kg", "value": 0.0, "__typename": "Weight" }
      },
      "shop": { "defaultWeightUnit": "KG", "__typename": "Shop" }
    }
  }
]
```
In the edit, I'm adding a size "super". There shouldn't be any conflicts there.

**Comment by NyanKiyoshi** [comment]
You mean that you have a conflict creating an attribute with the same slug/name than another attribute? This is the expected behavior. But this behavior will be dropped soon (see #4351).

**Comment by khalibloo** [comment]
The issue is with editing an existing variant attribute. Sorry the last example might not have been clear enough. Here are the steps:

1. I added a product type with a variant attribute "size" and gave it some options "mini", "med" and "maxi".
2. Next, I went back to edit the same product type. I added a new option to the "size" attribute ("super").

This should have worked, right? It has a different slug. But I got an error saying that the attribute (not attribute value) already exists.

**Comment by NyanKiyoshi** [comment]
That's really weird. Did you try on master and re-compiled the dashboard through `npm`?

I can't reproduce, I tried many things.

**Comment by khalibloo** [comment]
I last merged with master about a week ago. The bug only seems to occur when you have an attribute with the same name as another product type's attribute. For example, if I have Product Type A with a variant attribute called "Size", then if I add "Size" attribute to Product Type B, any attempt to edit it will result in this error.

**Comment by NyanKiyoshi** [comment]
I'm unable to reproduce. The issue was maybe fixed last week.

**Comment by khalibloo** [comment]
I have just updated my version. The issue is still present.

I also tried a clean install of saleor master branch to try to reproduce it, but the installation process fails due to mismatched hashes for graphql-relay python package. Try deploying a new instance on heroku and you should get the same error.

**Comment by khalibloo** [comment]
Ok, that's been fixed now. I've created a new saleor deployment using the Heroku button. I added a "Pokemon" product type and gave it a variant attribute "Size" with 2 options "small" and "big". Then I tried editing it, to add a new option "medium". And the bug is still there. Here's a link to it https://k-saleor.herokuapp.com/dashboard/next/product-types/
Or you can create a new deployment and try exactly that.

**Comment by khalibloo** [comment]
With #4351 this has been resolved
