### ISSUE TITLE
Implement customer events

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4039]
Once we get #4018 merged, we will want to implement the following as customer events:

	Model changes
		- [ ] Add a CustomerEvent model and types

	New Customer Events
		- [ ] the order was placed
		- [ ] a note was added to the order
		- [ ] downloaded digital link

	New Staff Events
		- [ ] A customer was deleted

	GraphQL Changes
		- [ ] A countable object from the CustomerEvent model
		- [ ] A `events` field in `customer`

**Comment by NyanKiyoshi** [comment]
IIRC we are allowed to log the customer's name during its deletion, even if they asked us to remove their data as it's not an information that could directly be used to identify a single person, a full name can return multiple persons (depending of the scope, of course). I'm believing it's fine for the GDPR as long we don't have any other information about this customer, other than their name. But I'm unsure.

We discussed about this issue during our previous meeting, and it was mentioned that @patrys may have an answer to bring us. What do you think about this matter?

We still have, of course, the issue of the orders; but that's another matter.

**Comment by patrys** [comment]
We are allowed to process a person's name as part of an order for the purpose of fulfilling a contract. We can do so even if the user requests that their data is deleted, otherwise it would be possible for me to demand that my data is erased from an unpaid invoice. We can use the buyer's data for as long as it's required: to process payments, dispatch packages for shipping, process complaints, returns, refunds, etc.

We can not use the information for any other purpose once the contract is fulfilled unless the user explicitly consents to such use (and that consent can be forfeited by requesting erasure). To me, that means we should probably avoid storing the information outside of the context where it's absolutely necessary for reasons required by law (order details, invoices, etc.). For events, it's probably safer to say "notified the customer" instead of "sent email to john.doe@example.com". We can't reasonably claim that it's absolutely necessary for us to put the name there for the purpose of fulfilling the contractual requirements (delivering purchased goods or services).

As for whether someone's full name constitutes personally identifiable information that really depends on the person. The regulation states that it applies to information that makes it reasonably easy to identify an individual. "Queen Elisabeth II", "Arnold Schwarzenegger", "Danny DeVito", "Taylor Swift" are all easily identifiable based on the name alone.
