### ISSUE TITLE
The voucher form doesn't show selected products

### ISSUE THREAD

**Issue by MahmoudRizk** [mirumee/saleor#4060]
### Steps to reproduce the problem
1. Open Voucher form.
2. Set Discount type to specific product.
3. Choose the products you want.
4. Create the voucher.
5. Open the created voucher from the list of vouchers.

What happens is the products field goes blank.

### What I expected to happen
The chosen products must show up when viewing the created voucher.

**System information**
Operating system:  Ubuntu 16.04
Browser:  Chrome.

**Comment by NyanKiyoshi** [comment]
Hi thanks for reporting!

After reproducing I see what you mean. When a voucher has selected products, the form doesn't show them. We can only see the products when we add them but not after saving or after a form error.

But, the products are saved, as we can see in the voucher list, it shows the correct number of products for the given voucher.

So the issue is most likely that the products are not being sent to the form for rendering.
