### ISSUE TITLE
Why Saleor dont use any Database cache enigne?

### ISSUE THREAD

**Issue by mmmcorpsvit** [mirumee/saleor#4222]
for example: 
1. https://github.com/Suor/django-cacheops
2. https://github.com/noripyt/django-cachalot

**Comment by korycins** [comment]
We prefer to fix wrong SELECT query instead of hiding it under a cache.
Query cache requires us to keep in mind which functions/methods need the newest data from DB and which one can be cached.  It could cause some problems eg: You always want to have a product's quantity up to date.
Instead of DB caching, we should think about caching the response from graphql's resolvers.
