### ISSUE TITLE
Deprecate the slug field for value input in attributes

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4345]
The client should be able to provide us with an `id` instead of a `slug`. (`AttributeValueInput`)

- We need to deprecate the field
- Update the tests

**Comment by g-londhe** [comment]
Hi @NyanKiyoshi,

Background:
I'm trying to create a product from an external application and I'm adding attribute value based on attribute-id right now.

Current scenario:
I'm getting attribute not found error once the attribute is deleted from the server or updated. As attributes ids are not in the human-readable format it's hard for me to check which attribute(attribute-id) has been deleted from the server.

It would be helpful if we have a slug option as input instead of id as an input while adding the product and its attributes via external apis.
