### ISSUE TITLE
2 BIG issue want to know if it fixed or not 

### ISSUE THREAD

**Issue by afhaider** [mirumee/saleor#4361]
someone placed order but not click on payment button product stock goes to OUT OF STOCK
also that missing product cannot be recover when clicking order detail their no remove order feature that user create a bug to that product 

recently found someone register with fake email id and place order tracking id nor email confirmation generated by this way creating a big issue 

#required feature
pip install django-simple-email-confirmation
#required feature
not lose product quantity until place payment successfully 
or provide period of time auto removal product stock recover if user not pay until 10min

---if required reply screenshot --

**Comment by afhaider** [comment]
By default, auto-add unconfirmed EmailAddress objects for new Users. If you want to change this behaviour, set settings.SIMPLE_EMAIL_CONFIRMATION_AUTO_ADD to False.
SIMPLE_EMAIL_CONFIRMATION_AUTO_ADD = False

**Comment by NyanKiyoshi** [comment]
Hi,

This is the expected behavior of the checkout workflow of the storefront 1.0. In the storefront 2.0/GraphQL API the payment is required to succeed before placing the order.
If it is really a big issue to you, you can always change its behavior.

Email verification is planned and is definitively something that we want to implement.
