### ISSUE TITLE
Integrate braintree local payment methods

### ISSUE THREAD

**Issue by JannikZed** [mirumee/saleor#4422]
### What I'm trying to achieve
I would like to integrate Braintree Local Payment Methods like documented here: https://developers.braintreepayments.com/guides/local-payment-methods/overview/

### Describe a proposed solution
To be more specific: we are currently integrating saleor in our german based webshop and would like to use SEPA direct debit as a payment method. We are able to create a merge request if we get some assistance on how to start and what is needed.

**Comment by JannikZed** [comment]
Hi there,
Still an open question - does somebody have an answer if the braintree integration is able to handle local payment methods like Klarna etc? 
This is needed on the server-side:
https://developers.braintreepayments.com/guides/local-payment-methods/server-side/python

**Comment by salwator** [comment]
Hi @JannikZed, 
Currently it does not support this out-of-the-box but you could create your own payment plugin based on _braintree_ that handles payment confirmation through webhook (which were recently added to saleor).
Such asynchronous checkout flow is in our plans for future development but it is unfortunately not on top of our priorities so, unless there is a community contribution, it will not be available soon in saleor.

**Comment by JannikZed** [comment]
Thank you for the fast answer! We will take a look into this - so you are saying, in general saleor core is already able to handle asynchronous tasks and you already added a needed webhook system? Could you give me some background on that? Maybe we can realize something for braintree.

**Comment by korycins** [comment]
Hi @JannikZed 
The backend part of the webhook is already done. We still don't have declared all possible events but we will add new ones in future releases. (If you need some new event you could also create PR. ;) )
Webhook uses a plugin logic for triggering asynchronous events.  This can be helpful if you want to have a different way to schedule tasks (e.g you don't want to use celery). 
Webhooks need to be assigned to ServiceAccount object and need to receive a list of events that webhook wants to subscribe to. ServiceAccount is an object to group and control assigned webhooks. You need to declare the exact permissions that you want to grant to a given ServiceAccount.  ServiceAccount generates by default the API token which can be used to get access to API.
You can check queries: `webhooks`, `webhook`, `webhookSamplePayload` and mutation - `webhookCreate`, `webhookDelete`, `webhookUpdate` - All these actions can be done by logged-in staff user (with expected permission) and by ServiceAccount (token provided in header). This is super helpful because you can automate a flow for subscribe and unsubscribe on the 3rd services.
Frontend part is ongoing now, here you can track a progress: https://github.com/mirumee/saleor-dashboard/pull/206
Thanks to this you will be able to create static webhooks (copy and paste a specific URL to connect Saleor with your service), list and manage all webhooks.
