### ISSUE TITLE
Address validation for `country_area` doesn't work for (e.g.) German states

### ISSUE THREAD

**Issue by jongreig** [mirumee/saleor#4600]
### What I'm trying to achieve

Whenever I try putting in a German state (e.g. `BAY` for Bavaria) for `country_area` in the GraphQL mutation for `customerCreate`, the field never saves when the address and customer are created. It seems to work fine for other country's regions—e.g. US states.

I had a look around, and it seems to be related to Google's i18n metadata not having any German states in its region data—which is strange because this seems to be standard (or should be, I would think).

In any case, ideally it would be preferable if there were a way to save whatever I put in `country_area`, even if the `i18n` package doesn't find a relevant region/state/province.

(Also somewhat connected but tangential—for some reason this isn't a problem with the `addressCreate`/`addressUpdate` mutations. But there it seems like there is no validation applied to addresses, compared to `customerCreate`/etc.)

### Steps to reproduce the problem
1. Create a customer either through the GraphQL mutation, `customerCreate`, or directly in the Dashboard (2.0).
2. Set the region/`country_area` to, e.g., `BAY`, and `country` to `DE`.

### What I expected to happen

The address created alongside the new customer would have `BAY`/Bavaria saved. So far this doesn't happen—the result is instead blank for the returned GraphQL field `countryArea`.

### Screenshots
*N/A*

**Comment by Kwaidan00** [comment]
Lack of the list of German states is not a reason of the problem. The problem is the `country_area` is not in `allowed_fields` in i18n metadata. It's correct: the name of the state is not a part of address in Germany (see https://www.deutschepost.de/de/b/briefumschlag-richtig-beschriften.html). 
I know it's a bit confusing; there could be a cases when we would like to store more information than it is required. It happens not only for Germany, but for Poland or United Kingdom too - for the same reason, that country area is not a part of the postal address.
Maybe we should discuss some mechanism for skipping that behavior, e.g. by adding some settings.
