### ISSUE TITLE
Product attributes not visible on product details page

### ISSUE THREAD

**Issue by likewhoa** [mirumee/saleor#4683]
### What I'm trying to achieve
See product attributes values on the product details page.

### Steps to reproduce the problem
1. Fresh master clone
2. Add two shirts with various size and color attributes
3. Go to product details page
4. No attributes under product description

### What I expected to happen
An html table as shown in https://github.com/mirumee/saleor/blob/65e00b0d1497d329320b33c8bcdbe1fa8febfb9d/templates/product/details.html#L200-L207 showing the product attribute name and value.

Python-3.7.4
Gentoo Linux kv 5.0.13
Chromium-77.0.3865.35

**Comment by maarcingebala** [comment]
I'm on newest master after running `populatedb` on fresh DB. Here is my product details page:
![image](https://user-images.githubusercontent.com/5421321/63835974-e662bd80-c978-11e9-8102-972216aecefe.png)

"Material: Cotton" is a product attribute in this case. If I understand correctly, it isn't rendered in your case?

**Comment by likewhoa** [comment]
> I'm on newest master after running `populatedb` on fresh DB. Here is my product details page:
> ![image](https://user-images.githubusercontent.com/5421321/63835974-e662bd80-c978-11e9-8102-972216aecefe.png)
> 
> "Material: Cotton" is a product attribute in this case. If I understand correctly, it isn't rendered in your case?

Try adding a new product with a custom attribute though. I only had issues with new products not existing ones.

**Comment by NyanKiyoshi** [comment]
Hi, @likewhoa thanks for the finding. I created a patch in https://github.com/mirumee/saleor/pull/4705. The issue was that the field `visible_in_storefront` of the `Attribute` model (`product_attribute`) was being set to `False` by default by the dashboard 1.0 due to mistake that was on the form.

To make your affected attributes appear, you have multiple possibilities:
- You could delete and recreate the attribute, the values, reassign the values to the products, etc. (hardest solution)
- You could update all attributes to be visible through SQL (`./manage.py dbshell`):
```sql
UPDATE product_attribute SET visible_in_storefront = TRUE WHERE visible_in_storefront is FALSE;
```
- You could use the [saleor-dashboard](https://github.com/mirumee/saleor-dashboard), go to the "Configuration" section, and in the attributes page, toggle the field `Visible on Product Page in Storefront` of the affected attributes and hit save.
<img width="352" alt="Screenshot 2019-08-30 at 22 19 06" src="https://user-images.githubusercontent.com/6186720/64049175-45405680-cb74-11e9-9682-8001088d07d7.png">
