### ISSUE TITLE
Stripe module has no attribute `create_form`

### ISSUE THREAD

**Issue by taoufik07** [mirumee/saleor#4691]
### What I'm trying to achieve
I was trying to use Stripe locally, so I've added the env vars and added stripe to the `CHECKOUT_PAYMENT_GATEWAYS`, but in the check when I choose the payment method and I proceed I got an attribute error `module 'saleor.payment.gateways.stripe' has no attribute 'create_form'`.

*I've checked in the stripe module but I couldn't find the `create_form` while it exists for other gateways

### Steps to reproduce the problem
1. Setup Saleor locally using docker 
2. Add Stripe env vars and Add Stripe to the `CHECKOUT_PAYMENT_GATEWAYS`
3. Go to the storefront, add an item to the cart and checkout
4. Choose Stripe as a payment method
5. Click proceed
6. The error occurs 

### What I expected to happen
See a Stripe form, enter my payment info

### Screenshots

![image](https://user-images.githubusercontent.com/22898667/63812633-3d41a600-c92b-11e9-931e-872e74b86a1a.png)

**Comment by salwator** [comment]
Hey @taoufik07,

Unfortunately new stripe implementation is not compatible with old saleor storefront and is accessible only through API due to Stripe API significant change (using _PaymentIntents_). We're not keeping backward compatibility for new code since we prefer to put resources into new SPA storefront.

You could easily roll back stripe gateway to old implementation but please consider it will stop working pretty soon in European Union due to **[SCA](https://stripe.com/au/guides/strong-customer-authentication)** regulation. 

You could also write _create_form_ for new stripe implementation on your own, that could additionally be very appreciated contribution 😉

**Comment by syusama** [comment]
> 
> 
> Hey @taoufik07,
> 
> Unfortunately new stripe implementation is not compatible with old saleor storefront and is accessible only through API due to Stripe API significant change (using _PaymentIntents_). We're not keeping backward compatibility for new code since we prefer to put resources into new SPA storefront.
> 
> You could easily roll back stripe gateway to old implementation but please consider it will stop working pretty soon in European Union due to **[SCA](https://stripe.com/au/guides/strong-customer-authentication)** regulation.
> 
> You could also write _create_form_ for new stripe implementation on your own, that could additionally be very appreciated contribution 😉

Hi@salwator ,
I've meet the same problem"module 'saleor.payment.gateways.stripe' has no attribute 'create_form'"
I just want to achive stripe,but have tried so much time.How to write create_form?
thanks!!!!!!!!

**Comment by salwator** [comment]
Hi @syusama,

There is an example of _create_form_ in _braintree_ gateway implementation in form of _BraintreePaymentForm_. Once you can _create_form_ method that returns usable form, your stripe integration with old saleor storefront should work fine.
You can use great stripe docs to learn [how to use PaymentIntents](https://stripe.com/docs/payments/payment-intents/web) on the web.
