### ISSUE TITLE
Hi, can you tell me what size in RAM requre saleor for hosting 

### ISSUE THREAD

**Issue by Menks** [mirumee/saleor#4704]
Hi, i customized my Saleor and i want to host my customized version but i don't know wath is the requirement in RAM and HD, can you please advice me for that and the best Hosting Provider

**Comment by mmmcorpsvit** [comment]
for build Nodes need 2 Gb RAM, in any case you can expand size use swap

**Comment by Menks** [comment]
Hi i searched an adequate (in price and technologies (python and postgreSQL) Hosting provider to host my Saleor and i found this Provider.
https://www.a2hosting.com/web-hosting/compare

Please can someone Help me by thelling me if it is possible and that is the mimimum offer (LITE ,SWIFT,TURBO) possible to choose ?

![Capture](https://user-images.githubusercontent.com/6191474/64292257-844a1f80-cf59-11e9-8ec8-a3bd5c07e176.PNG)
![Capture1](https://user-images.githubusercontent.com/6191474/64292259-844a1f80-cf59-11e9-925d-9294af387f14.PNG)

**Comment by NyanKiyoshi** [comment]
For the physical memory, 500MB/1GB should/can be enough. In depends on the case. If you are only having a few users per hour, 500MB is largely enough. The 1GB offer is not that much more expensive, might be a safer bet.

But we really can't tell you how much you need. But it looks like you are simply trying to deploy a small scale site, so it would be fine.

For what @mmmcorpsvit was saying, we recommend that you install the npm dependencies and compile the assets in your local machine, then push them into the production server. There is no point to compile the assets in the production server.

Also, @Menks, I note that the website says "Python 2.6, 2.7 or 3.2", is that true? 3.2 is no longer maintained by Python since 2014 (security updates, minor fixes, etc.) and Saleor requires at least Python 3.6 but we recommend using 3.7. Is there any way to install it manually? e.g. through `venv`.

If you are looking for something cheap and up to date that doesn't require "dev op" knowledge, you might want to look into PythonAnywhere (https://www.pythonanywhere.com/pricing/). The cheapest offer is way enough.

Also note that with PythonAnywhere, you can deploy a site for free to allow you to give it a try before paying for it.
