### ISSUE TITLE
Dynamic translations interface 

### ISSUE THREAD

**Issue by Zoxon470** [mirumee/saleor#4954]
Have you dynamic translation interface? I have read the documentation but I can't find interface for translation words. Our customer need translation interface.

PS I have some problem, I can't get product translation. I don't understand what the problem. I would be grateful for help.

1. I have created translation for my product
https://ibb.co/VWnc718
2. I have tried get product translation in graphql, but I get `"translation": null`
https://ibb.co/RC8wDnP

**Comment by maarcingebala** [comment]
We have a UI for that and it's available in the dashboard in the "Translations" section:
- documentation: https://docs.getsaleor.com/docs/dashboard/translations/
- demo: https://pwa.saleor.io/dashboard/translations/

About your second question, could you try adding the translation with this mutation and see if it works:

```
mutation {
  productTranslate(id: "some-id", input: {name: "Translated name"}, languageCode: EN) {
    errors {
      field
      message
    }
    product {
      id
      name
      translation(languageCode: EN) {
        name
      }
    }
  }
}
```

**Comment by Zoxon470** [comment]
@maarcingebala I have got this https://ibb.co/10CfdZX

**Comment by Zoxon470** [comment]
@maarcingebala 

I'm not using this dashboard https://pwa.saleor.io/dashboard/ , I use it https://github.com/mirumee/saleor/tree/master/saleor/dashboard there has section "Translations"? I can't find https://ibb.co/tPb31Sp

**Comment by maarcingebala** [comment]
On the last screenshot you're using the old dashboard, which doesn't support model translations. It's only available in [saleor-dashboard](https://github.com/mirumee/saleor-dashboard/).

In GraphQL you need to use Base64 encoded ID's instead of database IDs. E.g. in our [demo GraphQL API](https://demo.getsaleor.com/graphql/) you can run a query like this:

```
{
  product(id: "UHJvZHVjdDo3OA==") {
    name
  }
}
```

Where `UHJvZHVjdDo3OA==` is the GraphQL ID of the product.
