### ISSUE TITLE
Default extensions location

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor#4964]
IMO we should move plugins shipped with Saleor from `saleor.extensions.plugins` into `saleor` directory. Having it this way suggests it's default plugin directory and Saleor forks will end up having one, big `extensions` app.

@korycins Whats your opinion?

**Comment by korycins** [comment]
@krzysztofwolski, It sounds good but I am not sure if we don't want to extract all plugins into separate packages. 
@maarcingebala  Do we want to extract all plugins or only Payment plugins?

**Comment by maarcingebala** [comment]
I don't think it's an issue to have plugins in one directory; otherwise we would have one big `saleor` directory with mixed plugins and pure Django apps, which is worse in my opinion.
We definitely wanted to move payment gateways outside. As for other plugins, I think we need to wait until we implement more of them and we have a clear and stable structure.

**Comment by krzysztofwolski** [comment]
Sure, lets lee how it turns out 👍. 
I'll go with 'all in apps' approach and provide feedback later.

BTW Are there plans for having tests inside plugin folder or we have to wait for migrating whole project into changed tests structure?
