### ISSUE TITLE
Shipping calculation, totals and plugins

### ISSUE THREAD

**Issue by krzysztofwolski** [mirumee/saleor#4965]
### What I'm trying to achieve
Shipping price calculation plugin

### Steps to reproduce the problem
1. I’ve introduced plugin with overwritten calculate_checkout_shipping method
2. Now I can call the manager to get shipping prices, cool!
3. Now checkout total will be invalid: `manager.calculate_checkout_total` takes total from Checkout.get_gotal()
4. Checkout.get_gotal() takes shipping from Checkout.get_shipping_price(), which ignores plugin manager existence

### What I expected to happen
Using a plugin to modify shipping price also modify checkout total

@korycins Am I missing something?

**Comment by korycins** [comment]
The manager calculates only the default value (inside his body) which will be used in the case when you don't have any plugin with the method that the manager is gonna call.

Your case:
`manager.calculate_checkout_total` - calculates `default_value` base on `checkout.get_total(discounts)`. The manager wil pass it as a default_value but it is plugin responsibility to calculate `checkout_total`. You can do it by calling `calculate_subtotal` and `calculate_shipping` (see VatlayerPlugin - `saleor.extensions.plugins.vatlayer.plugin.VatlayerPlugin#calculate_checkout_total`) or you can create ther your own logic (see AvataxPlugin - `saleor.extensions.plugins.avatax.plugin.AvataxPlugin#calculate_checkout_total`).

So I assume that you can do it exacly what you want.
One thing that we need to change (probably) is "cooperation" between plugins. Plugins like Avalara or Vatlayer should use recieved `default_value` instead of calculating it directly from the checkout.

**Comment by krzysztofwolski** [comment]
After discussion on chat:
- manager.get_checkout_total should calculate using manager.get_checkout_subtotal() and manager.get_checout_shipping()
- logic for checkout.get_total should not be duplicated 
- checkout.get_total should be removed from the model, and moved to the utils package
