### ISSUE TITLE
Slug of product

### ISSUE THREAD

**Issue by pakhanthegod** [mirumee/saleor#4981]
### What I'm trying to achieve
Why Product model doesn't have a slug attribute? Product model creates it dynamically in `get_absolute_url` method:

```
def get_absolute_url(self):
        return reverse(
            'product:details',
            kwargs={'slug': self.get_slug(), 'product_id': self.id})

def get_slug(self):
        return slugify(smart_text(unidecode(self.name)))
```

### Describe a proposed solution
Add a slug attribute to Product model as other models have it. After that it would be possible to translate slugs for example in ProductTranslation model.

### Screenshots or mockups
![image](https://user-images.githubusercontent.com/30771990/68996447-eb6e4380-08bb-11ea-97df-112e6f2d97ad.png)

**Comment by NyanKiyoshi** [comment]
Hi! This is because the slug is for SEO. If the slug is no longer valid, it will be still handled by through the passed primary key of the product.

But you raise a good point for translation. I notice `get_slug` doesn't handle localization. It would be straight forward to do, including making sure the prefetches are properly done in the views.

@maarcingebala how should we handle this issue as we are planning on moving out of the django views in the next release?

**Comment by pakhanthegod** [comment]
Hi! Thank you for your answer. 

Now there are questions from your answer:
* In which cases can the slug be no valid? In my mind it's hard linked to a Product model where from we get the slug.
* So if it's about SEO why a Category model has the slug? It is doesn't created dynamically and taked from a model attribute then used in urlpattern.
```
url(
        r"^category/(?P<slug>[a-z0-9-_]+?)-(?P<category_id>[0-9]+)/$",
        views.category_index,
        name="category",
    ),
```
```
class Category(MPTTModel, ModelWithMetadata, SeoModel):
    name = models.CharField(max_length=128)
    slug = models.SlugField(max_length=128)
    ...
```

**Comment by maarcingebala** [comment]
Slug added was added to the `Product` model.
