### ISSUE TITLE
Admin Panel not visible

### ISSUE THREAD

**Issue by roshan172** [mirumee/saleor#5056]
I followed the documentation and populated the database, but when I tried to visit the dashboard URL it was giving me an Error message stating that the requested URL does not exist. Is that URL moved to some other place ??

**Comment by korycins** [comment]
https://github.com/mirumee/saleor/issues/4463
https://github.com/mirumee/saleor/issues/5017
https://github.com/mirumee/legacy-views

**Comment by em1le** [comment]
The documentation is unclear (part creating administrator account) and how to get a dashboard.

**Comment by korycins** [comment]
Hi @em1le,
We are always PR welcome, so if you see a place which needs changes you can create PR :)
About the docs:
We are still in the middle of dropping the old part of Saleor. We didn't have enough time to finish it and update the docs for the master. If you want to have up-to-date docs I recommend you to use the release version of Saleor (current 2.9.0) instead of the master branch.

**Comment by em1le** [comment]
Hi @korycins ,
I understand and if i have any free time soon it would my pleasure to help.
Although you made a great job in building the dashboard v2.
