### ISSUE TITLE
I cann't  config project Saleor(Version 2.9) on Macos .

### ISSUE THREAD

**Issue by theanhvo** [mirumee/saleor#5105]
1. Cann't run : npm run build-assets
2. Not see url home, dashboard in source .
Please help me,
Thanks very much Team.

**Comment by karolkielecki** [comment]
@theanhvo Hey. Could you please send us your error log?

**Comment by infinitecipher** [comment]
@theanhvo Hi what version of saleor are you using because in the most recent master. The frontend was separated into two separate repositories [Storefront](https://github.com/mirumee/saleor-storefront) and [Dashboard](https://github.com/mirumee/saleor-dashboard). Please follow the documentation for each one of those and run your backend at the same time.

**Comment by infinitecipher** [comment]
@theanhvo Hi what version of saleor are you using because in the most recent master. The frontend was separated into two separate repositories [Storefront](https://github.com/mirumee/saleor-storefront) and [Dashboard](https://github.com/mirumee/saleor-dashboard). Please follow the documentation for each one of those and run your backend at the same time.

**Comment by maarcingebala** [comment]
If you're using the `master` branch, you need to switch to the prerelease version of the docs which includes matching instructions: https://docs.getsaleor.com/docs/next/getting-started/installation-macos/.
