### ISSUE TITLE
Cannot create multiple values when they sometime can contain a special character

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#5132]
Let's say I want to sell processors having for possible socket attribute values:
- AM3
- AM3+
- AM4
- FM1
- FM1+

The following slugs would be created:
- AM3
- AM3
- AM4
- FM1
- FM1

Leading to being unable to create those values contain a `+` sign which has a totally different meaning.

**Comment by maarcingebala** [comment]
We will tackle this while working on #5196. In general, we want to unify the behavior of slugs. Few assumptions:
- `slug` should be unique across the system
- for some models, we generate slugs from names, but we should also provide an input field for slug in create/update mutations, so that users can always set it manually
- if `slug` is not provided in the mutation input, we will try to generate a unique value from by appending an incremental number to the name. Given the example above, we would generate the following slugs:
  - AM3: am3
  - AM3+: am3-2
That's a fallback solution until we add input fields in the UI so that users will be able to control the slugs for attribute values as well.
