### ISSUE TITLE
Expected one shopping basket per person and got 3 that switch everytime you load a different page

### ISSUE THREAD

**Issue by Cephlin** [mirumee/saleor#518]
I've been developing this site: http://crystal-nebulae-dev.eu-west-1.elasticbeanstalk.com/

and I've noticed that when I add something to the basket and refresh, there are 3 baskets for my login.

So if I refresh 3 times it shows the correct basket, but otherwise it shows a blank basket. The 2nd and 3rd basket can also have items added to them.

I shall leave the dev site up for now so you can test this, but I can't seem to figure it out. It does not happen when I run it locally, only in production.

**Comment by artursmet** [comment]
It may be caused by session storage in your production environment. Sessions are stored by default in redis, and default setting for redis storage is `locmem` https://github.com/mirumee/saleor/blob/master/saleor/settings.py#L29
Django dev server uses only single thread, so locmem acts normal, when you deploy to production you have to change this setting and use standard redis server, otherwise each thread will have it's own session storage. 

For example:
You have 3 threads on production, worker server (probably uWSGI) uses round robin algorithm for thread   pool. So after each refresh, you may hit another worker, since sessions are stored in thread's local memory, you will end up with three sessions.

**Comment by patrys** [comment]
@artursmet is right, you need a shared cache for your deployment. The default is to store sessions in local memory which means each of your server processes will have a different idea of what the current session is and what it contains.

**Comment by Cephlin** [comment]
Set it to 1 processor in production and I can confirm you're correct.

I'll configure it to use a redis server. 

Cheers.
