### ISSUE TITLE
Problem with payment_information

### ISSUE THREAD

**Issue by srendon** [mirumee/saleor#5193]
### What I'm trying to achieve
Hi Saleor team. I’m implementing my own payment gateway. For the checkout process I’m referring to [How to Create Checkout]( https://docs.saleor.io/docs/next/api-process/check-out/). When I send the `checkoutComplete` request in [process_payment(payment_information)]( https://docs.saleor.io/docs/next/guides/payments/#process-payment) I print the `payment_information` object which has this json: 

` PaymentData(amount=Decimal('22.82'), currency='USD', billing=None, shipping=None, order_id=None, customer_ip_address='172.18.0.1', customer_email='admin@example.com', token='01417a33-07d2-4897-a343-df956bc9544a', customer_id=None, reuse_source=False)`

The billing, shipping, order_id, and customer_id keys have a value of `None`. In both, my gateway and Dummy gateway, the json is the same. Is this a bug or I need to change something in order to retrieve  that information. 

### Steps to reproduce the problem
1. [How to Integrate New Payment Gateway](https://docs.saleor.io/docs/next/guides/payments/)
2. [How to Create Checkout](https://docs.saleor.io/docs/next/api-process/check-out/)
3. Print `payment_information` in [process_payment(payment_information)]( https://docs.saleor.io/docs/next/guides/payments/#process-payment)

### What I expected to happen
The billing, shipping, order_id, and customer_id keys should have their corresponding value.

**Comment by karolkielecki** [comment]
Hey @srendon! We'll investigate your issues as soon as we can. Thank you for your patience.

**Comment by Boquete** [comment]
Right now, payment is created before create_order() in checkoutComplete mutation

You can just move payment create after order_create and set payment.order_id or any other data from created order object.


Also, there's security flaw in saleor checkout / create_order mechanism, make sure to add extra feature to prevent changing lines in checkout objects, because right now it's possible to create payment, add items to checkout and use same payment information to pay for the order. Such order will be marked as FULLY_PAID as there is another bug in saleor in checkout total_amount (it uses payment object total instead of order total)

**Comment by patrys** [comment]
We're investigating why data is not carried over from the checkout sessions, you should not have to create the order object before processing the payment.

**Comment by maarcingebala** [comment]
@srendon @Boquete There was indeed an issue with passing data from checkout to payment gateways. I've made some changes in the internal functions to use checkout instance to get the billing and shipping addresses. `order_id` may still be empty since orders are created from checkouts after payment.

The `payment_create` function used to accept `billing_address` as an argument, which was confusing (and not used in the code anyway). At the time of creating payments, we should already have users billing addresses assigned to the checkout instance. Now, this is required to create payments successfully.

Please check if these changes solve the issue for you.
