### ISSUE TITLE
Multivendor Support

### ISSUE THREAD

**Issue by gulfpearl** [mirumee/saleor#520]
Does Saleor support multiple vendors?

**Comment by iraycd** [comment]
No. It doesn't support multi vendor. Django-oscar supports multiple vendors.

**Comment by patrys** [comment]
I guess it depends on your definition of requirements. We do support multiple stock records per item but there is no dedicated dashboard for partners to access.

**Comment by pcompassion** [comment]
I think `sku` of ProductVariant should be moved to Stock if we are to use multiple stock records?

**Comment by patrys** [comment]
If you want to track it by your partner's SKU (ie. you don't use GTIN/UPC and don't have your own stock) then yes. I think in most cases the store has their own stock code for everything on offer (for invoicing, warranties, returns etc.) in which case you either always use your internal code or you use both (and add `partner_sku` to the stock record).

**Comment by iraycd** [comment]
My suggestion is to have a separate `Partner` module and inside `ProductVariant`. Use,

    class Meta:
        app_label = 'product'
        unique_together = ('sku', 'partner',)

**Comment by patrys** [comment]
Closing this as it's mostly a discussion with no immediate actionable items.

**Comment by edevil** [comment]
@zadigus Hello! Did you reach any conclusion? I'm on the same boat.

**Comment by maarcingebala** [comment]
Hey, we have duplicated issues for that, let's use #1251 for discussion about multi-vendor.

**Comment by zadigus** [comment]
@edevil Yes, I reached conclusions. I never got any answer in this thread or by email from saleor's team on the topic. Therefore I am currently using saleor as a submodule in my project and extending that code so that it fits my needs. If you need more details, I can surely help you out. 

Since December 2018, we've continued working with saleor as it is much more lightweight than vue-storefront (we don't like Magento). Therefore we investigated saleor's database and found out how to extend the currently existing saleor database with multi-shops and multi-vendors (it's not done yet as we are implementing some other stuff right now, are a very little team with very little resources, but we documented everything on our private share; if you want to see how we develop this, feel free to either contact me or double-check our [project's repository](https://github.com/softozor/shopozor-backend)). Or maybe saleor made some progress on the topic.

The only thing that we are absolutely not enthusiastic about at the moment with this solution is that the graphql queries take ages to run (we started writing our acceptance tests and noticed this big inconvenience).

**Comment by edevil** [comment]
@zadigus Thank you for the pointers! The slowness with the API is with any queries in particular? It seems like an important issue...

**Comment by maarcingebala** [comment]
In version 2.0.0 we've added optimizers that dynamically add data prefetching, but some queries/mutations still suffer from database queries duplications. In fact, it's really difficult to fully optimize the graph since in the client you can query all kinds of combinations that may require a lot of joins underneath. 

The best solution would be to analyze the database queries and optimize them against queries that your frontend app uses. Also, if you're using Django Debug Toolbar, we noticed that it heavily impacts the performance of the API.
