### ISSUE TITLE
column product_productvariant.quantity does not exist LINE 1: ...S Col17, "product_product"."weight" AS Col18, SUM("product_p...

### ISSUE THREAD

**Issue by rajpatel-rp7** [mirumee/saleor#5288]
### Screenshots
![1](https://user-images.githubusercontent.com/49655582/75087368-4b345480-5565-11ea-9b72-c3d78fec5efb.PNG)

Error during template rendering
![2](https://user-images.githubusercontent.com/49655582/75087392-8df62c80-5565-11ea-8d74-013a01922f43.PNG)

**System information**
I install all of the setups and requirements step by step and all of that are Updated in the latest version.

What should I do?

**Comment by NyanKiyoshi** [comment]
Hi!

First of all, that's a old/previous version of saleor, so maybe your code is from an older revision than the database. I would recommend you to try to run `python manage.py migrate` and see if that's managing to update your database. If it still doesn't work, I would recommend you to start over with an empty database, migrate it, populate if you want to start over with a former version instead of bothering downgrading the database or such as you seem to be on a development mode, so data loss wouldn't be an issue.

Try the two suggestions above, and feel free to ask any more question if needed. And feel free to add which version or git hash, e.g. through `git describe` you are using and giving us the last migrations applied, e.g. `python manage.py dbshell` then `select * from django_migrations order by applied desc limit 20;`.
