### ISSUE TITLE
Editing models and database structure by hand in Saleor

### ISSUE THREAD

**Issue by tanishqkumar** [mirumee/saleor#5439]
Hi all! 

I recently forked Saleor 2.9 for a web app I am building for an art gallery that wants to display their products for sale as well as give their artists some publicity. I want to be able to have a bunch of cards (like "our team" components) that pull data from an Artists table on the back-end that stores information about the artists' names, emails, origins, etc, and then display it on the front-end. I am struggling to see how to modify the models/DB to create a new "Artists" table with name, email, info, and then to create a manyToMany-like relationship with the products I've populated in the DC, giving the products a "created by" attribute. There are tons of models files throughout the /dashboard directory, and even when I make changes to the core models to create an artist class, I don't know how to get it to show on the dashboard so artists can be created/modified from there. 

In the end, I would like to make it so that the client (non-technical) can add artists and have them show up on the artists page I will make, somewhat like products show up on their pages (but obviously I cannot create a new category "Artist" as artists cannot have prices or shipping as they are people; and there are other attributes I would want like email that a product cannot have, either. They are also different to staff on the website, so I cannot use the "staff management" functionality.)

I looked at [this](https://stackoverflow.com/questions/57237286/saleor-trying-to-modify-the-dashboard-add-job-title-to-customer-accoun) question but Saleor structure has changed since then, and that was a relatively minor attributal change to an existing class (User) as opposed to the creation and integration of a new class. I'm surprised that despite extensively searching for anything on how to do something as straightforward as create a new model there is little documentation and discussion online; I must be missing something. 

Please help :) Thank you!

**Comment by tomaszszymanski129** [comment]
@tanishqkumar There is no docs on how to add a model since we use pure Django for that, there is no hidden knowledge here.
- To create the `Artists` table you just create a class that inherits from `django.db.models.model`, then `docker-compose run web python3 manage.py makemigration` and `docker-compose run web python3 manage.py migrate`. That will create these tables in DB. Consider Artist model would possibly inherit from `User` model depending on your needs.
- If you'd like an m2m relation with products so one artist will have a field "products" that points to a queryset of products assigned to him, just add a field on `Products` model like `artist = models.ForeignKey(Artist, related_name="products")` then of course make and run the migrations again.
Entire app uses graphql to communicate via frontend-backend, just run dashboard or storefont and look in browser dev console to see how requests are made / build. graphql playground is also available at :8000 port.
- when you have the models you should create mutations for managing your new objects. We use 
[Graphene](https://docs.graphene-python.org/en/latest/) for that.
- After you have mutations in place you can proceed with frontend work.

**Comment by tanishqkumar** [comment]
Hi Tomasz--thanks for the response! When you say "proceed with frontend work", could you elaborate on how I would get all Artist-related info to show on the dashboard so it can be manipulated like everything else? I looked at forms.py in /dashboard, but that didn't seem to clear things up much either. And I assume I should just create the same type of mutations that other objects, like Products, have in Saleor within the creation of the new class?

Thank you :)

**Comment by tomaszszymanski129** [comment]
@tanishqkumar you would have to modify the dashboard code to your needs, entire dashboard (frontend) is a separate repository: [saleor-dashboard](https://github.com/mirumee/saleor-dashboard) - so you would need to create a separate view there that will allow staff user to manage Artist related things.
What do you mean by `forms.py in /dashboard`? Cannot see it in current code.

And backend-wise:
`And I assume I should just create the same type of mutations that other objects, like Products, have in Saleor within the creation of the new class?` - Yes, when writing mutations you can even inherit from our CRUD-like classes (ModelMutation and subclasses). On example how to create a new mutation for a model you can see my recent PR: https://github.com/mirumee/saleor/pull/5377/files There is a create invoice mutation written from scratch.

In general i've mentioned another repository here, so it's worth mentioning that saleor actually consists of three repositories (saleor, saleor-dashboard and saleor-storefront). First one is backend, 2nd is the "admin" dashboard and 3rd is the frontend users will use on your site to buy things. Don't know how you've set it up but for local development i recommend using [saleor-platform](https://github.com/mirumee/saleor-platform) which can set you up with these three quick and painless so you can jump into coding right away.

**Comment by tanishqkumar** [comment]
Hi Tomasz--

Thanks so much for your super helpful comments, I've been learning the mutation structure in Saleor and how the data flow pipeline is setup between front and backend. I also migrated to 2.9 whereas I'd been using a legacy version before. 

On an unrelated note but still to do with changing models and data flow, if I was interested in building a (different) app modifying Saleor to accommodate multiple merchants and their respective products, i.e. having a landing page where a user can choose to buy from Target OR CVS and THEN see THOSE products (just like they see products on the current home page)--would this just be a matter of having each merchant create a dashboard account and create products for their respective stores, and then a new landing page that routes the consumer to the merchant's store, accordingly, or does a change like this require a major revamp of many parts of the app? 

I ask because I am unsure as to whether Saleor is built to offer one consumer goods from many different possible merchants, and have many different merchants manage those orders in their own respective dashboards, or is just a standard ecommerce solution for one company selling their own goods. I don't think I understand the model structure (I wasn't even sure if there would have to be any models changes to accommodate several merchants on one site?) well enough to know if making this change involves just what I mentioned and whether it's doable on the scale of a few days/weeks, or will take many months. 

Thank you--Saleor's strong support for devs is making it one of my favorite platforms to build atop of!

**Comment by maarcingebala** [comment]
@tanishqkumar Thanks for the kind words! Saleor currently supports the second model which is selling goods from one merchant. Changing it to support the multi-merchant approach is not on the current roadmap. It would be a significant change and I wouldn't rule out that it would be available at Saleor one day, but this is rather a distant future. For now, we want to make sure that the single-merchant approach works really well.

**Comment by tanishqkumar** [comment]
I see @maarcingebala One last thing I wanted to ask was about how you suggest a developer make timelines with Saleor, given its size and organizational structure, for example with the art gallery commerce site I'm building atop of it. Having only ever built smaller (non-production grade) apps from the ground up, building something atop a codebase like Saleor which has 600,000+ lines of code, hundreds of models and mutations passed through several files each is certainly new and challenging to get my head around.

So far, I have spent time setting up the project and adding the Artist model (as Tomasz discusses in the above posts), but I have yet to write graphQL mutations for the new artist model discussed in posts above, to change the design and layout of three pages on the front-end (incl. pulling some Artists data from the back-end to display), add Google Analytics and Stripe integrations as well as deploy the whole project on S3/Heroku (having never used either before). I just wanted to ask how long you think this would take a single developer given your understanding of Saleor's codebase. Of course it will vary greatly according to time and intensity put in, but I just wanted to gauge whether my (clueless) estimate of 2-4 weeks full time is anywhere near accurate given your understanding of Saleor architecture. 

I appreciate this isn't really to do with Saleor's internal mechanisms and so you're going beyond your expectations if you give me some tips wrt this :) Thank you Marcin!

**Comment by maarcingebala** [comment]
My rough estimate would be:
- artist model and mutations/queries to manage it (and some tests) - 1 week if you know Saleor already, 2 weeks if you're not too familiar with Graphene/GraphQL.
- Stripe integration is already there, so enabling it in your project shouldn't require much work.
- Google Analytics - that's the frontend part and it may be as simple as adding one line with GA tracking ID
- customizing the frontend - it depends on how much changes you have, you want to use the basic theme that comes with Saleor and just add new views it shouldn't be much work (if you're familiar with React).

So I guess the 4 weeks estimate sounds real.

**Comment by maarcingebala** [comment]
You need to be aware that if you add new models and API directly in Saleor it may be more difficult to upgrade to new version of Saleor in the future, as you'll have to deal with merge conflicts. Another approach to avoid that is to create a separate small app that only does your specific logic and integrates with Saleor through webhooks/API. 

https://docs.saleor.io/docs/next/developer/extending

**Comment by tanishqkumar** [comment]
That's so helpful--by the way, did you guys update the docs? When I read them a few weeks ago they were nowhere near as detailed for developers as they are now. So far I'd been trying to learn about the code and architecture basically by reading lots of the source code. The developer pages look super helpful! I'll look into extension architecture but also wanted to ask about deployment with Saleor. 

I haven't used Heroku/S3 before, but how long do you think it would take to learn enough about S3/Docker to be able to deploy the app once built? I'll have to factor that into the timeline as my friends tell me deploying takes ages.

**Comment by maarcingebala** [comment]
The link that I've sent you is the new version of developer docs and it will be soon released as Saleor 2.10. "next" means that it's is not officially released and it's up-to-date with the `master` branch. You can switch to `2.9` docs which refer to the 2.9 release of Saleor (https://github.com/mirumee/saleor/releases).

I would say we were too focused on the code for a long time and the docs were a bit behind. Our goal for incoming sprints is to improve the docs with better documentation of the GraphQL API. Also, we want to add docs for [saleor-storefront](https://github.com/mirumee/saleor-storefront/) to explain how to use the SDK or customize the theme.

Heroku is probably the simplest way of deploying Saleor backend. As for the frontend (storefront) I haven't done this on Heroku - I personally use [Netlify](https://www.netlify.com/) for my own project which is pretty simple to set up as well. Configuring S3 should be also fairly simple, I'm sure there is a lot of resources online about S3 itself. This document describes env variables that you'll have to configure in Heroku so that it uses S3 for media/static storage: https://docs.saleor.io/docs/next/developer/running-saleor/s3

**Comment by tanishqkumar** [comment]
Hi @maarcingebala I've spent the last week learning graphQL, graphene, and studying the data flow through the front-end to the API and backend. I had a few general questions that couldn't easily be answered looking through all the docs, previous StackOverflow posts, and Gitter/Spectrum posts--any thoughts would be much appreciated:
- I'm a bit confused about how hooks are used in Saleor. In the Apollo Client tutorial, any and all mutations are used not by wrapping a component with a TypedMutation component, but by coupling data requirements _within the mutation itself_ by putting a useQuery or useMutationName hook _inside the mutation_ as opposed to wrapping it. Are all queries/mutations just defined in API and then used by wrapping components?
- When trying to add basic functionality for a new model (Artists, as above posts), is it really necessarily to build out the wealth of files that each Saleor model has? Each model has hundreds of mutations (eg in ProductMutations of saleor/graphql/product/schema.py and I was unsure of really how to go about making new mutations if all existing ones are this complex. Should I ignore complexity of current mutations/queries and just write the createArtist into a new folder's schema.py as one would expect having just finished the graphene/graphQL tutorials? 
- Similarly, on the the front end, the dashboard's products/components has tons of little components it uses in the views where it allows creation of a new product (eg LikeFilter, ImageSelectDialog). Houw could I get an approximation of the current create product view to make a create Artist view without writing all of these nuanced components myself?
- I see fixtures.ts a lot but still don't understand what it does in any of the folders in which it's used. 
- FInally, a question on the createProduct process with the API. It's not clear to me how the Product object is actually created in mutations/products.py—in get_instance you’re fetching something then in def save() saving that instance? But how does this create something from scatch/match up to the def mutate convention in graphene? 
- More generally, how can I find the answer this type of question about graphql and mutations—are there any docs/tips on how to create a mutation if you’re a graphql noob and have only just finished the tutorials? The current dev docs only mention what apps/plugins are in extending Saleor and say nothing about how to extend mutations etc. Perhaps this is because it's pure graphQL--but still how can someone understand the huge existing graphQL architecture?

Sorry for a long post, but I looked over everything you'd said and came up with these questions, and think they could be helpful for others in the future, too. 

Thank you so much!

**Comment by mgvel** [comment]
Editing models in saleor? Please spend your time elsewhere, by far the worst opensource project I have ever dealt with. To remove a single field from checkout form, we had to edit at least 50 different files. And still we are not able to complete the task. We could have simply built a Django project from scratch. 

I couldn't help, but this thought repeatedly comes to my mind if this design was intentional :thinking: ! 

Saleor used to be a djagno e-commerce project now it's a spaghetti monster of Django, Typescript, React, GraphQL and full of bloated code. 

I am willing to change my mind if somebody proves me wrong and shows a sane way to customize models and pages in the front-end.

**Comment by patrys** [comment]
@mgvel, I'm sorry to hear your story. I'm afraid I have to disagree with the sentiment. Headless, API-based applications are where modern stacks are moving. It sounds like you'd prefer a pure Django application with the server rendering HTML templates, and I get it because it makes it quick to hack.

But it's is not what Saleor is, and Saleor would never get to where it is today if it was built like a typical Django application from a decade ago. What you're calling a "spaghetti monster" is a multilayer API application where Django is limited to providing the persistence bit. Some of those layers have different representations of the same data; Saleor's GraphQL API is separate from its database schema, while it does mean that some fields need to be added to or removed from multiple files, it means we can improve our API without changing how we store the data. It means we can change how we store the data without breaking the API compatibility.

I get it that someone familiar with Django having to learn a frontend framework like React or a language like TypeScript sounds like jumping through unnecessary hoops. And you could very much implement a Python app that talked to Saleor using its API and used Django templates to render data, Django forms to handle input, and so on. But that's not how storefronts are built today. Some experiences are impossible to implement without a stateful client-side app and are simply impractical to hack together using jQuery. More and more "websites" are actually browser apps talking to a host of independent headless services. "Frontend work" no longer means sprinkling some CSS over whatever the backend returns. Client-side applications are getting so complex they need vast test suites of their own. We rely on tools like Storybook to represent the myriad of different states a UI can be in to avoid spending the entire day meticulously reproducing each one of them.

As for modifying the code, we're building Saleor to make it extendible. We provide APIs like attributes and metadata, webhooks, pub/sub queues, and other tools that allow you to build on top of Saleor without modifying the core. The ease of directly hacking the code is not a priority for us; the maintainability of the resulting stack is. And being able to upgrade Saleor when there's a security release is an important part of that.

I'm not saying this to prove you wrong. I see what you went through and I feel your pain. All in all, it seems like you really need "a Django project" and not an entire GraphQL-based "monster".

**Comment by mgvel** [comment]
Thanks for the prompt reply and my sincere apologies for venting out my frustration. I mean no disrespect, I really like and enjoy how the new version of saleor looks compared to old Django version's dashboard. 

I have learned TypeScript, React and GraphQL just to utilize and learn more from you guys. I will still point out what is making me struggle with Saleor. 

- When using a reactive programming model like React, why still auto updates are not working in dashboard without needing to refresh
- Whenever  I was running the docker-compose version, there are some crypto-mining bots spawning in my computer. I have tried to block port-by-port from redis, postgres, and other services. And yes, I have repeated this process in multiple computers with different OSes (Fedora, Debian, CentOS, Ubuntu). If I stop the docker process, miners disappearing. I have even tried to put my own images one-by-one to track down which image is bugged, without success. It's probably not Saleor's fault. But I am not confident to run this in production. 
 - I will be more than happy and indebted to you if you could point me in the right correct direction to customize. For example, checkout page address form has too many fields, for a simple a restaurant website that's not only excessive but also bad user experience. What are the list of files I should edit to achieve this behavior? If there is no need to edit the saleor core, I will not do that. 
- There is a Django layer, GraphQL query handler and still why form fields are hard coded in the front-end? 
- Detailed documentation is missing for deployment, customization etc. 

Once again thanks for such a great project. If I was a hater I wouldn't;t have bother coming in here. I feel so much attached to saleor. In another issue I asked how could I add simple print order button  in dashboard, there was no help for months then what I got was an one liner saying roughly `it is possible now`. 

Apologies for my harsh words, I do maintain some projects I know the pain doing that.

**Comment by patrys** [comment]
@mgvel The storefront is not meant to be part of "Saleor" per se, it's merely a demonstration of how Saleor (a headless API) can be used to build a commerce site. While we're still working on a project better suited to act as a starter kit, most of our customers are happy to build their own storefronts from scratch.

For the dashboard, we are working on an API that would allow Apps to inject their own widgets into the UI but it's not there yet. If you need this today, you can edit the dashboard to add the button there but I would encourage you to consider making the button call an API external to Saleor (for example a lambda function) and use that external service to fetch the necessary data from Saleor and eventually post the results back to Saleor.

I can't really help with the crypto-mining bots. We do no such thing in our Docker images and I'd be interested to see how you've discovered the problem and if we could reproduce it.

**Comment by thetooth** [comment]
@patrys the storefront repo should be deleted. It is overly complex for someone to learn anything from and only serves as a means of frustration when trying to get a dev environment up (on my computer it takes about 3 minutes of 6 cores being maxed out before it gleefully proclaims half the files are missing and thus never actually works, 2.11 branch compiles but crashes whenever opening a product lmao).

It's the same deal with the tax system, we don't use VAT here and avatax hasn't bothered activating our account for about a month so there is no way of calculating taxes without writing a plugin when this functionality should be part of the core and not outsourced to a 3rd party that may drop off the face of the earth at any moment as it seems to be the case right now.

Not trying to bash saleor too hard but I do think if more focus was put on actually getting existing features in the API to work rather than stacking on dozens of new features and libraries at every chance you'd actually have a product with some real utility behind it rather than a liability to anyone that dares to adopt it.

**Comment by Megidd** [comment]
According to my experience, I believe storefront existence is pretty helpful. I deployed as production all three components of *api*, *dashboard*, and a customized *storefront*. Well, to be honest, I didn't get into customizing *storefront* heavily, but I love so far.
