### ISSUE TITLE
Missing payment_captured and order_fully_paid events

### ISSUE THREAD

**Issue by dsarmiento84** [mirumee/saleor#5535]
### What I'm trying to achieve
When placing orders using a gateway that captures the amount (without using the dashboard), the events payment_captured and order_fully_paid are not registered. These events are registered only when marking orders as paid in the dashboard.

### Steps to reproduce the problem
1. Make an Order.
2. Pay using Dummy (fully-charged) or a credit card Gateway.
3. Look into table order_orderevent.
4. Events payment_captured and order_fully_paid are missing.

### What I expected to happen
I expect these events registered when capturing a payment.

Thanks and awesome project!

**Comment by maarcingebala** [comment]
Thanks for reporting, it's a bug. These events should be called as well when an order is placed through checkout mutations.

**Comment by dsarmiento84** [comment]
Hi, this seems to be caused because order object is not set up correctly in payment object (is None when capturing a payment). Do you have any clue where in the code this can be happening (so I can debug it myself)?

**Comment by koradon** [comment]
@dsarmiento84 @maarcingebala 
Hi, I believe that this is because in checkout flow we create order after the payment is done.
We could create those events when we create order but then we introduce edge cases when we capture the payment and don't create an order for some reason.
Another solution would be that we create an event without order and for example checkout token and then after placing order, we update the event with it.
