### ISSUE TITLE
Reponse image from API giving http over https

### ISSUE THREAD

**Issue by Yaghdev** [mirumee/saleor#5739]
i am running query  
query ProductsList {
  shop {
    description
    name
    homepageCollection
    {      
      id      
      backgroundImage 
      {
        url
      }
    }
  }
}

but the image url is without https where as in setting .py ssl_enable is true.
{
  "data": {
    "shop": {
      "description": "",
      "name": "Kalawati Super Market",
      "homepageCollection": {
        "id": "Q29sbGVjdGlvbjoy",
        "backgroundImage": {
          "url": "http://....../media/collection-backgrounds/clothing.jpg"
        }
      }
    }
  }
}

please help me out of this

**Comment by robertology** [comment]
I would like to understand the source of this. It would help me know better how Saleor works (I'm new to anything Django).

From my exploring, I would think the decision *should* be [here](https://github.com/mirumee/saleor/blob/81c12c7daf53dc56be7d67012309ba35712b0611/saleor/core/utils/__init__.py#L30) but [this call](https://github.com/mirumee/saleor/blob/81c12c7daf53dc56be7d67012309ba35712b0611/saleor/graphql/core/types/common.py#L250) doesn't actually end up in that method even though that's the only place I can see it being defined.

.
.
.
…before submitting that reply, I realized the `context` there must be some built-in or 3rd party thing. Turns out [it's in Django](https://docs.djangoproject.com/en/3.1/ref/request-response/#django.http.HttpRequest.build_absolute_uri)  (side question: why does Saleor have its own defined?)

> Mixing HTTP and HTTPS on the same site is discouraged, therefore build_absolute_uri() will always generate an absolute URI with the same scheme the current request has.

So, I believe what you're seeing is due to the page you've loaded *not* being `https`
