### ISSUE TITLE
JS in static not work

### ISSUE THREAD

**Issue by Chhunneng** [mirumee/saleor#5909]
### What I'm trying to achieve
I want JS file is working. I add more code to navbar.js but it is not showing the console when run
### Steps to reproduce the problem
1. I want to change navbar in phone
2. 

### What I expected to happen
I test for the console in navbar.js but in web no console heppend

### Screenshots

**System information**
Operating system:

**Comment by maarcingebala** [comment]
Hey, there are no JS files in Saleor now, since a few versions this repo only contains the API. If you're referring to [saleor-storefront](https://github.com/mirumee/saleor-storefront) please open the issue there. If you're using the old Saleor with Django-based views, we no longer maintain it, it is archived here: https://github.com/mirumee/legacy-views.

**Comment by Chhunneng** [comment]
Thank !
