### ISSUE TITLE
Product API

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#617]
Category and search pages should be available with rest API which can be consumed later with some js like React.

API structure will be discussed later

**Comment by artursmet** [comment]
@benekex2 Please suggest an API  structure required to render category pages and search results as single page.

**Comment by benekex2** [comment]
@krzysztofwolski to discuss

## Endpoint: /products/

### Parametrs:
?search: string
?category: number
?size: string
?color: string

?min_price: number
?max_price: number

?sort_by_price: boolean
?sort_by_color: boolean
?sort_by_size boolean

### Example Response:
```
[
	{
		"id": 1
		"name": "Product 1",
		"url": "http://localhost:8000/products/product_1",
		"image_url": "http://localhost:8000/images/image.jpg",
		"category_id": 1,
		"category_name": "default",
		"category_url": "http://localhost:8000/products/category/default/"
		"price": {
			"min": 50,
			"max": 70,
		 	"currency": "USD"
		},
		"discount_value": 10,
		"is_available": True,
		"is_in_stock": True,
	}
]
```
## Endpoint: /products/filters/

### Parametrs: 
?category_id number - Return subcategories

### Example Response:
```
[
	{
		"id": 3,
		"name": "Color",
		"type": "checkbox",
		"values": [
			{
				"id": 5,
				"value": "red"
			},
			{
				"id": 6,
				"value": "green"
			},
			{
				"id": 7,
				"value": "black"
			}
		]
	},
	{
		"id": 2,
		"name": "Size",
		"type": "checkbox",
		"values": [
			{
				"id": 3,
				"value": "A4"
			},
			{
				"id": 4,
				"value": "A5"
			}
		]
	},
	{
		"id": null,
		"name": "Categories",
		"type": "radio",
		"values": [
			{
				"id": 1,
				"value": "Default"
			},
			{
				"id": 2,
				"value": "Kubki"
			},
			{
				"id": 3,
				"value": "Kubki do wody"
			}
		]
	}
]
```

**Comment by krzysztofwolski** [comment]
@benekex2 For now for filter choices I'm using attribute ids - example: ```?color=1```. It will be changed to ```?color=red```
Todo: 

- [ ] add slug field for attributes


 
## Endpoint /product/filters
Instead of using names like 'checkbox' I would use:

- 'choice' for single choice filters (example: In stock filter (yes or no))
- 'multiple_choice' when multiple values can be specified (example: category filter)
- 'float' for numerical values (example: prices)

For _choice_ and _multiple_choice_ possible values are stored under 'values' key.

Example output 
```json
[
    {
        "values": [
            [
                5,
                "red"
            ],
            [
                6,
                "blue"
            ],
            [
                7,
                "white"
            ]
        ],
        "type": "multiple_choice",
        "id": 3,
        "name": "color"
    },
    {
        "values": [
            [
                3,
                "A4"
            ],
            [
                4,
                "A5"
            ]
        ],
        "type": "multiple_choice",
        "id": 2,
        "name": "size"
    },
    {
        "values": [
            [
                1,
                "Default"
            ],
            [
                2,
                "Kubki"
            ],
            [
                3,
                "Kubki do picia"
            ],
            [
                4,
                "Kubki do picia wody"
            ]
        ],
        "type": "multiple_choice",
        "name": "category"
    },
    {
        "type": "float",
        "name": "price_from"
    },
    {
        "type": "float",
        "name": "price_to"
    }
]

```

**Question**: @benekex2 Is there anything more you need to render filters? Any additional types?

## Endpoint /products/

### Pagination
Variables:

- _page_ - number of actual page. Current default: 1
- _per_page_ - items per page. Current default 25

Links to next/prev/first/last page are stored in links header. 
**Question**: what default values should be used for _per_page_ setting?

### Sorting
Variables:

- _sort_by_ - name of variable the items will be sorted by. Multiple values allowed. Current default: pk ascending

To sort descending add "-" in front of name. Example: ?sort_by=-pk

**Question**: Which fields we want to sort?  

### Filtering

Variables: any name from filters described in Product Filters endpoint. 
Example:
```/products?price_from=20&price_to=100``` - returns items with price between 20 and 100
```/products?color=1&color=4``` - returns items described by color with id 1 or 4


Example output: 
``` /products/?category=4&category=1&page=4 ```

```json 
[
    {
        "category": {
            "id": 4,
            "name": "Kubki"
        },
        "name": "Harrison Ltd",
        "url": "/products/harrison-ltd-2/",
        "price": {
            "from":  62.1,
            "to": 62.1,
            "currency": "USD",
            "discounts": null
        },
        "in_stock": true,
        "image_url": "/static/image.jpg",
        "id": 2
    },
    {
        "category": {
            "id": 1,
            "name": "Default"
        },
        "name": "Moore, Dennis and Barber",
        "url": "/products/moore-dennis-and-barber-3/",
        "price": {
            "from":  15.2,
            "to": 15.2,
            "currency": "USD",
            "discounts": null
        },
        "in_stock": true,
        "image_url": "/static/image.jpg",
        "id": 3
    }
]
```

**Comment by elwoodxblues** [comment]
I'm closing this issue, as we decided to give a try to GraphQL. The related project: https://github.com/mirumee/saleor/projects/2
