### ISSUE TITLE
Simplify stock management when there's only one StockLocation

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#669]
When there's only one `StockLocation` object present, dashboard should display `num_in_stock` field directly on product form (the same way as SKU field is displayed, when product class has no variants)

**Comment by krzysztofwolski** [comment]
Simplification of stock management needs more discussion. Simple merge of stock form into product form will introduce too many fields (and indicators of available and allocated quantity).
IMO current stock management is clear enough. Good improvement would be adding option to ignore stock management for some variants.
Example: We have book with 2 variants - Hardcover and digital. First has default stock management, second one has no need to track quantity and allocation since it's digital product. 
@artursmet this looks like task for next milestone, do you agree?

**Comment by artursmet** [comment]
Yes, let's postpone it and discuss digital products use case for the next sprint.

**Comment by patrys** [comment]
We want to have stock tracking and shipping as switches on product class level. We don't want to mix physical and digital variants, they are entirely different beasts.

**Comment by julienfabre** [comment]
Any news on this issue?
What would be the best way to handle digital products (i.e. no stock management needed) at this time?

**Comment by patrys** [comment]
It should be enough to disable stock tracking at product class level.

**Comment by julienfabre** [comment]
I'm somewhat new to the project, could you be more specific? I'm familiar with the shipping switch on ProductClass (`is_shipping_required`), but not with a stock tracking switch.

**Comment by Pacu2** [comment]
Stock model was dropped in #1996, it lives now within ProductVariant model.
