### ISSUE TITLE
API and Technical Documentation

### ISSUE THREAD

**Issue by osamaeshtiaq** [mirumee/saleor#7353]
### What I'm trying to achieve
To understand the backend structure which is turning out to be extremely vague due to lack of API and technical documentation.

### Describe a proposed solution
A library can be used to integrate with graphene and generate API documentation.

**Comment by krzysztofwolski** [comment]
@osamaeshtiaq API documentation is already documented:
https://docs.saleor.io/docs/3.0/developer/api-reference/api-introduction

**Comment by onecrayon** [comment]
I completely agree with the OP; the GraphQL schema is indeed documented (to some extent), but there is very little documentation describing the underlying model relationships and logic. For instance, I needed to create a product through GraphQL. I can infer some things (like the fact that a ProductType ID is required means I need to create a ProductType first), but there's nothing outlining the process, which involves something like 4-8 distinct GraphQL calls. I had to create products by hand in the dashboard, monitor the network requests in my browser's inspector, and extrapolate from there. Things like the fact that you need to add a Product to channels via one GraphQL mutation, and then later assign prices to the ProductVariant through another are non-obvious because the underlying relationships are often opaque.

Basically, the docs do an alright job of describing how to query an already-populated store, which is good for our eventual front-end developers. The GraphQL automatic schema documentation is awesome once you know what's going on under the hood (though a lot of the descriptions are terse to the point of uselessness), but gaining that knowledge is currently reliant on trial and error, which is frustrating and time consuming.

**Comment by mirekm** [comment]
👋 Thank you @onecrayon, it's pretty spot on! We're getting it and we plan to dedicate way more time and resources to our documentation any moment soon.

1. Would you mind sharing the most pressing topics we should cover from your perspective so we can include it during our next documentation workshop?

2. Would you be interested in participating in a bigger community workshop/hackathon dedicated to docs?
