### ISSUE TITLE
Introduce Settings model

### ISSUE THREAD

**Issue by artursmet** [mirumee/saleor#741]
Sometimes is useful to have Settings model, that keeps some site-wide settings, which can be changed without a deploy (using the dashboard).

Settings should be connected with `django.contrib.sites` to allow usage in multi-site envrionment as well.

**Comment by patrys** [comment]
`django.contrib.sites` are a terrible thing as they are cached as instances at process level. Because of the caching technique all models reachable through relations of the `Site` object are also cached and never refreshed from the database.

See https://code.djangoproject.com/ticket/15894 and all of its duplicates.
