### ISSUE TITLE
Instructions for Integration with FB

### ISSUE THREAD

**Issue by acs254** [mirumee/saleor#762]
I have followed the instructions for integration with Facebook, the ID/secret are variables on my Heroku dynos, my app is live on FB dashboard, and I have added "facebook" as a social application in the admin. But for some reason, I'm not seeing FB as an option on the sign in page. Are there additional steps I need to follow?

**Comment by artursmet** [comment]
Hello, @acs254 there I have fixed facebook login in Saleor: https://github.com/mirumee/saleor/pull/766
We'll work more on documentation soon, so this process will be documented for sure. Basically we're using django-allauth package and all providers that are delivered by this package, can be used with saleor as well.

**Comment by acs254** [comment]
Hello @artursmet thanks for the quick fix! Similarly, is there any documentation on how to integrate payments? I've used Stripe for other projects and like it, but I'm unsure of how to integrate with Saleor.

**Comment by artursmet** [comment]
@acs254 As I said - we'll work on more detailed documentation, but saleor is using django-payments to integrate with external payment processors, so you can refer to this package documentation: http://django-payments.readthedocs.io/en/latest/modules.html#stripe

Integration with Stripe should be pretty straightforward, because you only have to define payment variant in settings.py and add a choice to `CHECKOUT_PAYMENT_CHOICES` tuple. For stripe there's a dedicated template that will render stripe button. StripeCard backend in supported as well.

**Comment by krzysztofwolski** [comment]
Login error is not fixed. Task for better auth docs is opened here #881 
Closing.
