### ISSUE TITLE
Rounding for Payment

### ISSUE THREAD

**Issue by uroybd** [mirumee/saleor#7663]
### What I'm trying to achieve
In some currencies (at least in BDT), fractional payment amount is a problem (especially in cash on delivery). You can't even pay in the fractions since we don't have coins for them in circulation anymore. Some sort of optional rounding mechanism is needed.

### Describe a proposed solution
I don't have any. However, for my current project I have to modify the total checkout amount calculation (I might have to add an 'adjustment' field to the `TaxedMoney` type for transparency in the calculations.), and add fields for adjustment money fields in the order. I don't think doing it in plugin-level will be possible.

**Comment by MJD07** [comment]
Just run a banking app. Clone that app, on the cloned app make it so you
can adjust the amounts of cash you have. Call in the ime...  instead of
registering the whole card registering to the decimal closest to. Then
riker up your account your clearing anything before the other imei I gets
hit up so as you are approvaled before actually proof seen you can run a
card from a cloned app banking and just adjust your amount no in person
calls and you have a one way door inside the mine that sees you do it.
