### ISSUE TITLE
Improve Search 

### ISSUE THREAD

**Issue by john-neg** [mirumee/saleor#937]
Attributes fields doesn't included in search results
For example on demo.getsaleor.com store we have some items with this info "Publisher: Mirumee Press". If we search for Mirumee Press we get nothing. Only name and description are included now.
Same feature should be in Dashboard too.

**Comment by elwoodxblues** [comment]
We're going to add filtering in list views in dashboard. By default we search items by name and I'm not sure if we should index attribute values as well. What we could have is the ability to filter the search results by attributes, as it is possible in category view. The problem is that the results may come from different categories and we would have to figure out what filters to display. We could investigate it closer while rewriting our search backends (@salwator @patrys).

**Comment by cesarob** [comment]
I wanted to open an issue and it is related to his one I think. Search isn't integrated with normal categories navigation. If you reach a product from the search the rendered page should be the same that with the categories navigation.
