### ISSUE TITLE
Best practice to install hstore extension

### ISSUE THREAD

**Issue by tillkolter** [mirumee/saleor#977]
I hesitate to switch the shop database user to superuser. What is your practice to install migrate  `product 0021`?

**Comment by patrys** [comment]
That's a very good concern.

From security point of view the best way is probably to run migrations using a separate user from your normal database user. There is not reason for your regular user to be able to alter the schema for example.

For convenience however you can think about the separation later and create the extension manually using a separate privileged account. The migration should proceed if it detects the extension already present in the database.

For even more convenience if you recreate local databases often, you can manually create the extension in the `template1` database as this is the template used to provision newly created databases.

I'll keep this open and mark it as documentation because our docs need a better description of the database setup process.

**Comment by tillkolter** [comment]
I thought so too, that I could simply install the extension in `psql` and then proceed migrating, but it seems that the command `CREATE EXTENSION IF EXISTS ...` still checks if the user has the appropriate permissions even if the extension has been installed. I also tried to simply fake the migration product 0021, but there is probably more going on under the hood in the migration, because the following migration was then missing a `dict` datatype.

I ended up running the migrations with superuser credentials and then switched the user afterwards. 

I am still just developing locally so that is all more a theoretical concern to me, but I think it makes sense talking about, because users having problems with this will come up sooner or later I guess.

**Comment by umasslowellmj** [comment]
Looks like this is the issue about error im getting when I run migrate.py
#######################################################
django.db.utils.ProgrammingError: permission denied to create extension "hstore"
HINT:  Must be superuser to create this extension.
#######################################################

I am not postgres sensei, can anyone help me how to get through this error?

**Comment by umrashrf** [comment]
Bump

**Comment by maarcingebala** [comment]
@patrys Do you think we should mention that in the "Running your own server" docs?

**Comment by patrys** [comment]
@maarcingebala Goog question, I think you're right and we should mention in there.
