### ISSUE TITLE
Back button from detail page to navigate back to product list

### ISSUE THREAD

**Issue by tillkolter** [mirumee/saleor#981]
My first Saleor shop project (record shop) is rapidly evolving which is quite nice considering the fact, that I have no long term front end experience and I had to touch every model due to my customer's legacy data schema (+MySQL 👎 ) which can not be redesigned at the moment. I am pretty stoked about Saleor, because the codebase is just so easy to get started with. Awesome project!

However, I am getting a little tired about the loading spinner when I go back from the detail page to the product list. Are there any plans to implement a detail page with Relay and then just have a "back" button? I think this could save a lot of requests.

**Comment by elwoodxblues** [comment]
Hey @tillkolter, it's very nice to hear that Saleor is helping you! 
Actually we've had the discussion about migrating product details page to React a few times already, since we've added the category page that uses React and Relay. However, this is not our priority right now but it's definitely in our long-term plan. Our first priority would be extending the GraphQL API to allow people to write Saleor's storefront entirely as a Single Page App.
Regarding your problem, how long does it take to load the product list in your case? How many products do you have in the database?

**Comment by tillkolter** [comment]
The load times are around 800ms with DEBUG=False, my database has about 150k product entries + relational objects.

In the meantime my development took two turns:
1) I implemented a detail view myself 😊
2) The customers requirement for an audio player with continous playback in the main frame forced me to leave Django frontend-wise and completely rewrite the storefront which I now started (with ViuJS + Apollo).

**Comment by patrys** [comment]
FWIW we're also planning to switch from Relay to Apollo. Main reason is we want to switch to TypeScript and drop Babel (and Relay is a Babel plugin).

**Comment by elwoodxblues** [comment]
@tillkolter Sounds good, I'd love to see Saleor's storefront made in VueJS. I'm closing this issue for now and if you need any help feel free to open a new one. Also, if you came up with some improvements to the GraphQL API that could be ported to Saleor, a PR is welcome:)
